### ISSUE TITLE
Do new exports using Base16 templates

### ISSUE THREAD

**Issue by actionless** [themix-project/oomox#102]

**Comment by Mauladen** [comment]
[Gruvbox](https://github.com/shosca/base16-gruvbox/blob/master/xresources/base16-gruvbox.dark.xresources)

**Comment by actionless** [comment]
@Mauladen this ticket is about using the same template format as you linked for exporting all base16-supported themes from oomox, not about adding more base16 themes

all current base16 themes will be removed from ./colors/ after this will be implemented: https://github.com/actionless/oomox/issues/101

and afterwards all base16 themes will be added again but in their native format
