### ISSUE TITLE
weird shadows

### ISSUE THREAD

**Issue by INTRCPTR** [themix-project/oomox#138]
There is a starnge shadow that is applied to any oomox theme I generate. I use bspwm, so I have applyed the gtk3.css fix for tiling wms thinking that maybe that is what it refereed
 too, but no luck. It only appears sometimes when my gtk app is focused.

![oomox issue](https://user-images.githubusercontent.com/29486373/38046069-383418ee-3284-11e8-92e1-16761d1debdc.png)

**Comment by actionless** [comment]
you shouldn't have any border at all with that gtk.css fix applied, mb something is not wired fine

**Comment by INTRCPTR** [comment]
My border in the image comes from my wm bspwm, border on focused window.

**Comment by actionless** [comment]
and what is your gtk+3 version?

**Comment by INTRCPTR** [comment]
3.22.29

**Comment by INTRCPTR** [comment]
thunar and pcmanfm

**Comment by INTRCPTR** [comment]
tried using materia
![oomox-bug_scrot](https://user-images.githubusercontent.com/29486373/38097586-623734d4-333b-11e8-9d2e-e432a54deecc.png)

**Comment by actionless** [comment]
with oomox the issue looks similar to https://github.com/actionless/oomox-gtk-theme/issues/23, i'll have a deeper look if it's related

for materia, @nana-4, please have a look

**Comment by nana-4** [comment]
I guess @INTRCPTR is actually talking about what [`overshoot`](https://github.com/actionless/oomox-gtk-theme/blob/master/src/gtk-3.20/scss/widgets/_overshoot.scss) for `scrolledwindow` sometimes stays without disappearing properly.

I could (sometimes) reproduce this issue on gnome-shell with **any** themes (including Adwaita, Arc, etc). So I don't think this is an oomox/materia specific issue.

I think this is an upstream issue, so IMO this can be closed.

**Comment by nana-4** [comment]
@INTRCPTR Can you reproduce this issue with other themes (e.g. Adwaita, Arc, etc)?

**Comment by INTRCPTR** [comment]
I installed numix darkblue and my first issue can be reproduced with numix themes so far. I figured it was oomox because I didn't have other numix themes. The Materia issue i cannot reproduce unless it's that specific theme. I had this issue in the past but never bothered with it.
