### ISSUE TITLE
Issue exporting on ubuntu 17.10

### ISSUE THREAD

**Issue by Daxx367** [themix-project/oomox#141]
I have just installed oomox on ubuntu 17.10.1 server (using it as a clean platform for a i3 install).

When I try to export theme I am getting inkscape dbus proxy and connection errors. I'm rather new to this side of linux, mostly just basic server admin stuff so sorry if this is a stupid issue.

**Comment by actionless** [comment]
do you have inkscape installed? can you open it normally?

**Comment by Daxx367** [comment]
Inkscape started first time when I tried this morning but the theme still won't export. 

Is there anything that could be interfering with the connection?

**Comment by Daxx367** [comment]
Ok it was stupid user error, turns out that dbus wasn't installed on the system, so you can close this.

Sorry

**Comment by actionless** [comment]
@smurphos should it be added to the deps of ubuntu package?

**Comment by smurphos** [comment]
I'm very surprised it is not installed by default - loads of packages depend on dbus including systemd and dpkg.

**Comment by Daxx367** [comment]
It should be noted that I installed dbus-x11. 
It wasn't installed because I started with a Ubuntu server installation, I was most definitely an edge case.
