### ISSUE TITLE
ERROR: Destination directory does not exist.

### ISSUE THREAD

**Issue by throwyourboatsgently** [themix-project/oomox#145]
I'm trying to run oomox on both an up to date Manjaro KDE arch based system, and an ubuntu 17.10 system. I get the same "ERROR: Destination directory does not exist." error, when trying to export Materia themes. Numix themes do not work either, but Instead of getting an error message the build window simply closes after a few seconds. 

I installed oomox on Manjaro by running yaourt -S oomox-git
I installed oomox on ubuntu with gdebi and the 1.6.0 .deb package

Here is a photo of the error:
![image](https://user-images.githubusercontent.com/19699718/38690299-cbee23d6-3e4b-11e8-98bb-82e553e45039.png)

I also noticed this at the start of the build screen:
![image](https://user-images.githubusercontent.com/19699718/38690415-0ed1ba46-3e4c-11e8-889e-f52fcff6edfd.png)

Any help would be greatly appreciated. If you need more information from me please let me know what to provide, and instructions on how to fetch the relevant info. Thanks.

**Comment by actionless** [comment]
is there anything created in `~/.themes/` directory?

**Comment by actionless** [comment]
also please run `oomox-cli /opt/oomox/colors/retro/clearlooks` in the terminal and paste the whole output

**Comment by throwyourboatsgently** [comment]
ad2@airdyne:~$ ls -la /home/ad2/.themes/oomox-clearlooks
total 48
drwxrwxr-x 11 ad2 ad2 4096 Apr 12 16:17 .
drwxrwxr-x  3 ad2 ad2 4096 Apr 12 16:17 ..
drwxr-xr-x  2 ad2 ad2 4096 Apr 12 16:17 assets
drwxr-xr-x  4 ad2 ad2 4096 Apr 12 16:17 cinnamon
drwxr-xr-x  2 ad2 ad2 4096 Apr 12 16:17 gtk-2.0
drwxr-xr-x  3 ad2 ad2 4096 Apr 12 16:17 gtk-3.0
drwxr-xr-x  3 ad2 ad2 4096 Apr 12 16:17 gtk-3.20
-rw-r--r--  1 ad2 ad2  415 Apr 12 16:17 index.theme
drwxr-xr-x  2 ad2 ad2 4096 Apr 12 16:17 metacity-1
drwxr-xr-x  2 ad2 ad2 4096 Apr 12 16:17 openbox-3
drwxr-xr-x  3 ad2 ad2 4096 Apr 12 16:17 unity
drwxr-xr-x  2 ad2 ad2 4096 Apr 12 16:17 xfwm4
ad2@airdyne:~$ 


weird that shows output but pcmanfm and ranger show nothing:
![image](https://user-images.githubusercontent.com/19699718/38702240-17f08bd0-3e6e-11e8-86b4-64cedad27a25.png)

**Comment by throwyourboatsgently** [comment]
sorry about the lines through everything. I am a total noob when it comes to github and don't know how I should be posting the term output

**Comment by actionless** [comment]
now try `lxappearance` app, what it shows

**Comment by throwyourboatsgently** [comment]
It does show the oomox-clearlooks theme

**Comment by throwyourboatsgently** [comment]
lol I'm a moron I was looking in ~/.config/.themes instead of ~/.themes

I made the ~/.config/.themes folder manually after getting that error in the gui thinking that was where themes would be stored and maybe oomox couldn't create it if it didn't exist. Oddly enough I am no longer getting an error in the gui and both numix-based themes and materia themes export correctly. Everything seems to be working perfectly now, but I have no clue why running oomox-cli once fixed the error oomox-gui was having. Thanks a bunch for your help, and if you need any more info from me let me know.

**Comment by actionless** [comment]
https://github.com/themix-project/oomox-gtk-theme/blob/master/change_color.sh#L203

**Comment by feer9** [comment]
![screenshot_20180831_185553](https://user-images.githubusercontent.com/19179353/44937427-9b0ad480-ad4f-11e8-9ee7-cd1b2c69ecd5.png)
I can even reproduce the error if I delete the ~/.themes folder
I'm on Ubuntu 18.04 with KDE Plasma 5.12.6, and I just installed oomox from the .deb version 1.7.0.2-4-ge6688017

**Comment by actionless** [comment]
but oomox theme doesn't have any png assets, file the issue to the theme in which that problem happens accordingly
