### ISSUE TITLE
Add custom templates via GUI

### ISSUE THREAD

**Issue by ohnonot** [themix-project/oomox#146]
I hope I got the terminology right.

What I desire:

An option for the GUI to add templates I have written myself, so e.g. in addition to those the Materia theme already offers, I could add one for tint2, dunst etc.  
Those manually added should also override those already present, so e.g. a manually added gtk2 template would override the one built into the theme.

Afaics, the individual `change_color.sh` scripts already have the capability to do this, all that's missing is integration into the python GUI.

**Comment by actionless** [comment]
> Afaics, the individual change_color.sh scripts already have the capability to do this

not really, it allows to choose which of already existing templates to use, but it not allows to add more external templates

so far i recommend you to add tint2, dunst or whatever else template is missing directly to oomox-gtk-theme or materia-theme accordingly

if you'll still need to override those you could just make a user plugin (they're loaded from `/.config/oomox/plugins/`)

**Comment by ohnonot** [comment]
Thanks for the quick reply!

> add tint2, dunst or whatever else template is missing directly to oomox-gtk-theme or materia-theme accordingly

this is what I'm currently doing, but i still have to hack around inside `oomox_plugin.py` and `change_colors.sh`, no? that's why I cloned the theme folder first, but I don't like that I'll then miss future updates to the theme.

> if you'll still need to override those you could just make a user plugin (they're loaded from /.config/oomox/plugins/)

so this needs to contain at least `oomox_plugin.py` and probably the whole folder structure as found in an existing plugin, but I could reduce it to only provide, say, tint2 & dunst configs?

Not ideal, but better than copying the _whole_ theme, and thus removing it from version control.

**Comment by actionless** [comment]
for just adding a new template you don't need to modify oomox_plugin.py but only change_color.sh:

https://github.com/themix-project/oomox-gtk-theme/blob/aa9081b2899d7e8ba8ae47543173d2d9f0f13921/change_color.sh#L79-L92
