### ISSUE TITLE
Build and install instructions?

### ISSUE THREAD

**Issue by ltpour** [themix-project/oomox#148]
I'm trying to install oomox on Gentoo, I've done it before but I don't remember how. Was there perhaps a Makefile or something like it for one of the earlier releases? On one of my systems I've got a bunch of oomox executables under /usr/bin and I don't think I manually copied them there.

I'm using oomox with pywal, and it expects to find oomox-cli somewhere in $PATH. Copying everything under gtk-theme to /usr/local/bin and renaming change_color.sh to oomox-cli seems to work, but that's kind of a nasty solution.

**Comment by actionless** [comment]
it should be few ebuilds somewhere in the internets, the first i've found:
https://github.com/natefelt/fxlt-overlay/commit/2f24635e9d87e1dbd23837035a3e14ed1a073498

install script (more or less distro-agnostic) is here:
https://github.com/themix-project/oomox/blob/master/packaging/install.sh

**Comment by ltpour** [comment]
Thanks, the install script did the trick.
