### ISSUE TITLE
Error on exporting theme

### ISSUE THREAD

**Issue by InfraOrder** [themix-project/oomox#151]
Hello.
I have been using oomox for a while with no issues, however I recently did a fresh install of Arch. But now when I try to export a theme (whether it be through pywal or using the gui) I get this issue:
`Error opening output file: No such file or directory
make: *** [Makefile:23: css_gtk3] Error 1
make: *** Waiting for unfinished jobs....
Error opening output file: No such file or directory
make: *** [Makefile:31: css_gtk320] Error 1`

any idea how I can correct this issue? Possibly i'm missing a package?

many thanks.

Apologies if this is a noob question.

**Comment by actionless** [comment]
try it in the commandline and paste the command and full output

**Comment by InfraOrder** [comment]
Hi thank you for the quick response, very sorry, I'm uncertain how to do this...

**Comment by actionless** [comment]
`oomox-cli /opt/oomox/colors/retro/clearlooks`

**Comment by InfraOrder** [comment]
This is what I get,

`rm: cannot remove '/home/nate/.themes/oomox-clearlooks': No such file or directory

Building theme at /home/nate/.themes/oomox-clearlooks

rm -rf "gtk-3.0/dist"
mkdir -p gtk-3.0/dist
mkdir -p gtk-3.20/dist
mkdir -p cinnamon
sassc -I "gtk-3.0/scss" "gtk-3.0/scss/gtk.scss" "gtk-3.0/dist/gtk.css"
sassc -I "gtk-3.20/scss" "gtk-3.20/scss/gtk.scss" "gtk-3.20/dist/gtk.css"
sassc -I "cinnamon/scss" "cinnamon/scss/cinnamon.scss" "cinnamon/cinnamon.css"
rm -f "gtk-3.0/gtk.gresource"
rm -rf "gtk-3.20/dist"
rm -f "gtk-3.20/gtk.gresource"
rm -rf "/home/nate/.themes/oomox-clearlooks/dist"
Error opening output file: No such file or directory
make: *** [Makefile:23: css_gtk3] Error 1
make: *** Waiting for unfinished jobs....
Error opening output file: No such file or directory
make: *** [Makefile:31: css_gtk320] Error 1
`

**Comment by InfraOrder** [comment]
Update: I had ccache enabled in my /etc/makepkg.conf. 
Disabeling it removed the issue. 

Sorry about that.

**Comment by actionless** [comment]
i have no clue how ccache could be related but i'll try to reproduce the problem with it

**Comment by InfraOrder** [comment]
Hi, after doing some more digging into what caused it, I think what caused it was this line in my .bashrc:

`export MAKEFLAGS="-j9 -l8"`

I can create the issue again by uncommenting it, so it was this that was causing it, not ccache.

**Comment by actionless** [comment]
now it makes more sense

**Comment by actionless** [comment]
fixes in themix-project/oomox-gtk-theme#aed4f1fe0dcc0850269c27cfb0d6bfcc4b63788c
