### ISSUE TITLE
Selected Icons Turn Black When Window Out of Focus, Thunar 1.8.*

### ISSUE THREAD

**Issue by shimapan-mode** [themix-project/oomox#157]
As the title says, the selected icons in Thunar 1.8.0 and 1.8.1 turn black for some reason when another window is in focus.
Doesn't happen with other themes or the original Numix theme, same for all icon sets.

<details><summary>Screenshots</summary>
<p>

Thunar window in focus:
![Thunar in focus](https://a.doko.moe/ilvprd.png)

Thunar window out of focus:
![Thunar out of focus](https://a.doko.moe/uilzbg.png)

</p>
</details>

**Comment by actionless** [comment]
what WM/DE do you use?

**Comment by shimapan-mode** [comment]
bspwm

**Comment by shimapan-mode** [comment]
Some more info:
- distro: gentoo
- sassc - 3.4.7
- librsvg - 2.40.18
- glib - 2.52.3
- gdk-pixbuf - 2.36.12
- gtk+ - 3.22.30

Thunar 1.8.* is using GTK+3.

**Comment by shimapan-mode** [comment]
Just installed nautilus. Same issue.
![](https://a.doko.moe/vjtajn.png)
![](https://a.doko.moe/wnenzq.png)

**Comment by actionless** [comment]
that looks like GTK's `:backdrop` but i thought it's supported only in GNOME and Cinnamon

**Comment by shimapan-mode** [comment]
Also, it's not just brightness that changes, but color as well.
![](https://a.doko.moe/pigjio.png)
![](https://a.doko.moe/nghmno.png)

**Comment by actionless** [comment]
yeah, it seems what one of backdrop values is mixed with TXT_BG, i am now installing bspwm to try it in Xephyr (backdrop is not working in awesome or openbox)

**Comment by shimapan-mode** [comment]
Since the issue is related to the theme colors, I just tried some dark themes besides oomox, like Adwaita Dark and Arc Dark and the same thing happens apparently. The icons get darker when the window is out of focus, although it's not as noticeable since those themes are not as dark as the one I'm using.
So I guess it's not an oomox issue then..

**Comment by actionless** [comment]
@shimapan-mode i know for sure gtk-3 have some hardcoded widget parts not fully ruleable by themes (for example Inset/Outset/Groove/Ridge frames or some outline properties) so it could be a case

however i can't say for sure because i don't know how to introspect iconview with gtk inspector

**Comment by shimapan-mode** [comment]
@actionless it's not `:backdrop`, it's `:active`, check it
![](https://a.doko.moe/feizfd.png)
![](https://a.doko.moe/ixqcsl.png)
![](https://a.doko.moe/scwssu.png)

**Comment by shimapan-mode** [comment]
Well, I suppose I'll just save that css bit in `.config/gtk-3.0/gtk.css` then.

**Comment by actionless** [comment]
thanks for helping to debug this, i've pushed a fix

since you a gentoo user, mb you'll have a look on a ebuild? https://github.com/themix-project/oomox/issues/153

**Comment by shimapan-mode** [comment]
np, I'd love to help with the ebuild, but I don't have experience writing ebuilds, and I've got exams coming up real close so I can't afford to procrastinate any longer..
I'll help out if the issue is still active after a couple of weeks
