### ISSUE TITLE
arc theme does not generate gnome-shell theme

### ISSUE THREAD

**Issue by carlos22** [themix-project/oomox#160]
Even with "Generate theme for gnome-shell" the result does not contain a gnome-shell theme. With materia theme it works.

**Comment by actionless** [comment]
if it's working for you manually?

```
cd arc-theme
mkdir distrib
./autogen.sh --prefix=$(readlink -e ./distrib/) --disable-light --disable-dark --disable-cinnamon --disable-xfwm
make install
```

if result (in ./distrib dir) will be the same -- report it to arc theme instead

**Comment by carlos22** [comment]
Yes this works: `distrib/share/themes/Arc/gnome-shell` exists and seems to be correctly generated. 
Used  https://github.com/actionless/arc-theme/tree/c49e1f7fb0aa937789f7c2430c74479e66b6b230

Does also work with the AUR oomox version `1.7.0.2-5` if called directly with the described method.

Odd: Arc-Darker is still generated (and there is no gnome-shell).

**Comment by actionless** [comment]
>Yes this works: distrib/share/themes/Arc/gnome-shell

does that means what you are trying to generate a transparent theme? if not the right path would be distrib/share/themes/Arc-Solid/gnome-shell

**Comment by actionless** [comment]
found the problem: https://github.com/NicoHood/arc-theme/pull/118

thanks for reporting!

**Comment by actionless** [comment]
you can try it now in `oomox-git` aur package

**Comment by carlos22** [comment]
No does not work, and how should it the repo and the submodule are not updated yet?!

**Comment by actionless** [comment]
you right, updated the submodule

**Comment by carlos22** [comment]
Now it works. Thanks :-)
One question remains: is it always the non-dark variant?

**Comment by actionless** [comment]
thanks for testing!

your remaining question you have to ask in arc-theme upstream repo

**Comment by carlos22** [comment]
I think the original arc-theme generates three different ones (Arc, Arc-Dark and Arc-Darker). I want to have the dark one as I'm using the "Menu/toolbar background" as #44444 - but the shell background is still light. So it is not an upstream issue (there i can choose between the three generated flavours).

**Comment by actionless** [comment]
> I think the original arc-theme generates

show me

**Comment by carlos22** [comment]
```
cd arc-theme
mkdir distrib
./autogen.sh --prefix=$(readlink -e ./distrib/)
make install
```

`distrib` now contains `Arc/gnome-shell` `Arc-Darker/gnome-shell` and `Arc-Dark/gnome-shell` with different assets and styles. The `change_color.sh` script does only generate one shell theme of course.

**Comment by actionless** [comment]
but what about using custom autogen options?

```./autogen.sh --prefix=$(readlink -e ./distrib/) --disable-light --disable-dark --disable-cinnamon --disable-xfwm
```
