### ISSUE TITLE
Arc build error

### ISSUE THREAD

**Issue by cyrinux** [themix-project/oomox#163]
Hi,

Thanks for this cool project !
 
Since last git version, running archlinux, i can't build my Arc theme. This fail quickly with:

```
== Converting theme into template...
cat: ./common/gtk-3.0/3.20/sass/_colors.scss.thpl: No such file or directory

```
Say me if you need something more.

Regards,

**Comment by actionless** [comment]
`pacman -Qi oomox-git`

**Comment by actionless** [comment]
i found the problem and reverted submodule, but it seems what it next major oomox release arc support will be dropped: https://github.com/NicoHood/arc-theme/commit/58330c4a5b588249a570924c5e12343fb0103cfc

**Comment by cyrinux** [comment]
My version was 1.7.0.4.r3.g32fbb48d-1, i see the arc support will be maintained ;)
Thanks for help :)
