### ISSUE TITLE
Error: 0.25294 isn't a valid CSS value.

### ISSUE THREAD

**Issue by supersambo** [themix-project/oomox#164]
I'm using oomox via pywal which worked perfectly until recently when it started to throw the following error:

```
Error: 0.29412 isn't a valid CSS value.
        on line 340 of gtk-3.20/scss/widgets/_view.scss
>>   border: 1px solid alpha($borders_color, (lightness($bg_color))/100% + .2);
   ------------------------------------------^
make: *** [Makefile:31: css_gtk320] Error 65

```

The issue was [first raised in the pywal project](https://github.com/dylanaraps/pywal/issues/192) but seems to be an oomox problem.

**Comment by actionless** [comment]
which oomox version do you use

**Comment by supersambo** [comment]
according to (yaourt) I'm using oomox-git 1.7.0.5-2

**Comment by actionless** [comment]
then it should be already fixed (see related discussion: https://github.com/themix-project/oomox/issues/162)

otherwise you need to provide more steps to reproduce it

**Comment by supersambo** [comment]
I removed and reinstalled oomox via yaourt and it's working again
