### ISSUE TITLE
Problem with libsass 3.5.4-1

### ISSUE THREAD

**Issue by den731** [themix-project/oomox#166]
The recent update did not allow pywal to apply gtk theme. I am running Arch 4.18.12 with i3 (oomox-git 1.7.0.5-2). When libsass updated from 3.4.9 to 3.5.4 I had this error

    ...libsass.so.0 cannot open shared object
    make: *** [Makefile:23: css_gtk3] Error 127

Downgrading libsass to 3.4.9 solved this problem.

**Comment by actionless** [comment]
looks like borken arch installation

**Comment by den731** [comment]
Thank you
