### ISSUE TITLE
Suggestion: GUI improvements

### ISSUE THREAD

**Issue by nana-4** [themix-project/oomox#168]
@actionless Are you interested in improving the GUI? Oomox already has a nice GUI, but I came up with several ideas to further improve GUI, so i'd love to share it. :-)

Here's the mockup:
(Please ignore the style values. Also please note that `[...]` means omission.)

![image](https://user-images.githubusercontent.com/9556384/46919705-07027d00-d01e-11e8-9866-ba4b78e2cf03.png)

Notable changes are:

#### Overall

- Remove extra padding of main window (including "_Presets:_" and "_Edit:_" labels.)

#### Middle Edit View

- Adapt a design pattern to the lists based on the [GNOME HIG](https://developer.gnome.org/hig/stable/lists.html.en).

- Merge "_Theme options_" and "_Other options_" selections.

#### Sidebar

- Separate type and name (with folder and items). This improves readability and avoids spreading the sidebar wide.

- Split presets and user saved styles with separator. This allows users to easily find their own styles.

- Rename "_contrib_" to "_Others_" for easy understanding by end users.

#### Headerbar

- Convert the 4 icon buttons on the left to text-based button/menu-items. Since those icon buttons are not so clear their roles at a glance, IMHO.

- Rename "_Clone current theme_" to "_Save as..._". (Both "_Clone current theme_" and "_Save as..._" are functionally (almost) equivalent in this case, but the latter is more familiar words and should be easier to understand.)

- Put all the "_Export ***_" buttons that spread out horizontally into a single "_Export_" menu button.

- (Optional) Add "Keyboard Shortcuts" and "About Oomox" items into the primary menu as per the [GNOME's new recommendation](https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement). (Especially having an About screen would be helpful to know the version in GUI.)

---

Any comments/criticisms are welcome. (I don't mind even if you reject or partially adopt this.)

**Comment by actionless** [comment]
thanks a lot for a great research work, it looks really good on the preview!

i'll comment point by point to give you more information on how easy/quickly each of the changes could be adapted in few hours

**Comment by actionless** [comment]
just a quick comment about sidebar spitting -- after adding import button i was actually planning to split it into 3 sections:
1) plugins (plugins are displayed as folders and theme imported via each plugin are stored under those folders)
2) default themes (as on your preview)
3) user themes (as on your preview)

**Comment by actionless** [comment]
#### Overall

> - Remove extra padding of main window (including "_Presets:_" and "_Edit:_" labels.)

i don't mind, the only concern i have if it won't be misguiding for new users.
even with the current super-simple interface i saw few comments on reddit what "it's too complicated to make theme using oomox"

#### Middle Edit View

> - Adapt a design pattern to the lists based on the [GNOME HIG](https://developer.gnome.org/hig/stable/lists.html.en).

it looks visually better but will require quite a lot of work because there is quite a number of things which are relying on the fact what it's one list, not several separated lists

- Merge "_Theme options_" and "_Other options_" selections.

that's matter of each theme plugin, see https://github.com/themix-project/oomox/blob/master/plugins/theme_materia/oomox_plugin.py#L55-L78 for example

#### Sidebar

- Separate type and name (with folder and items). This improves readability and avoids spreading the sidebar wide.

for this i don't know what should be the behavior when user selecting with keyboard or mouse the directory, not theme itself

- Split presets and user saved styles with separator. This allows users to easily find their own styles.

this i commented above

- Rename "_contrib_" to "_Others_" for easy understanding by end users.

obviously nothing complicated :-)

#### Headerbar

- Convert the 4 icon buttons on the left to text-based button/menu-items. Since those icon buttons are not so clear their roles at a glance, IMHO.

i don't know how much mouse users will be happy with this change

- Rename "_Clone current theme_" to "_Save as..._". (Both "_Clone current theme_" and "_Save as..._" are functionally (almost) equivalent in this case, but the latter is more familiar words and should be easier to understand.)

yup, i wasn't able to come up with a right wording from the beginning :-)

- Put all the "_Export ***_" buttons that spread out horizontally into a single "_Export_" menu button.

the same as about 4 icons, idk if it would be good change for mouse users

- (Optional) Add "Keyboard Shortcuts" and "About Oomox" items into the primary menu as per the [GNOME's new recommendation](https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement). (Especially having an About screen would be helpful to know the version in GUI.)

shouldn't be complicated, i think it also could be useful during build/packaging process also somehow store `git describe`s of each submodule to show them also in the version window

**Comment by actionless** [comment]
@nana-4 i think soon i'll have time to start implementing those; could you please give some final feedback on still opened questions?

**Comment by nana-4** [comment]
@actionless I sincerely apologize for my late reply. For some reasons I couldn't take the time. Sorry...

And thanks for your reviewing!

> just a quick comment about sidebar splitting -- after adding import button i was actually planning to split it into 3 sections: [...] what do you think about it?

I'm not sure I understand it correctly, but honesty I don't feel the benefit of splitting "import plugins" and "user themes". For users, both are just user's one (not default one), aren't they?

> those themes are now displayed as normal but Xresources also an import, from xrdb; also if you think of random theme, it also imports some values from /dev/random :D

Hmm, I see. (Even though I'm not sure I understand it correctly,) but I personally don't think classifying them as "default themes" is a problem, as they are displayed by default. :)

> i don't mind, the only concern i have if it won't be misguiding for new users.

I don't have that concern. Since Many GTK+ apps have that pattern (paned window without labels), I think misguiding will rather decrease.

> it looks visually better but will require quite a lot of work because there is quite a number of things which are relying on the fact what it's one list, not several separated lists

Aha, sorry, I didn't care so much about that. :P

> that's matter of each theme plugin, see https://github.com/themix-project/oomox/blob/master/plugins/theme_materia/oomox_plugin.py#L55-L78 for example

So, does it mean that it is difficult to merge `theme_model_other` into `theme_model_options`? (Sorry, I'm not sure what you are telling.)

I just wondered why they are separated, even though both should be same _theme options_.

> for this i don't know what should be the behavior when user selecting with keyboard or mouse the directory, not theme itself

I imagined nothing will happen when user selecting the directories. See `gtk3-demo`'s sidebar for example.

> obviously nothing complicated :-)

Aha, okay :) (I just thought "contrib" sounds like developer-friendly, but not user-friendly. Well, but please never mind :P)

> i don't know how much mouse users will be happy with this change
> the same as about 4 icons, idk if it would be good change for mouse users

I know these changes increases mouse click action once. However, I quite believe these changes will improve understandability. In other words, it'll no longer "too complicated" for (some) users, I believe.

FYI, this mockup has been strongly influenced by GNOME's latest mockups (e.g. [icon-preview.png](https://gitlab.gnome.org/Teams/Design/app-mockups/blob/master/icon-preview/icon-preview.png) and [todo.png](https://gitlab.gnome.org/Teams/Design/app-mockups/blob/master/todo/todo.png)).

**Comment by nana-4** [comment]
However, indeed it is controversial to arrange "Save" button next to "Export" button: Users may be a bit confused.

It may be better to rearrange "Save" as a menuitem above "Save as...".

**Comment by actionless** [comment]
so most of the points seems to be clarified by now, but changes of the top toolbar are still seems to be somehow controversial. i suggest prioritizing them to the end of the queue, mb we'll have more feedback from the users

**Comment by nana-4** [comment]
Okay. I have no objection. :)

**Comment by actionless** [comment]
btw, i created a project to track the progress of all the upcoming GUI improvements, feel free to add specific tickets into that projects:
https://github.com/themix-project/oomox/projects/1

**Comment by actionless** [comment]
@nana-4 i've addressed some of the requests today, please check it out

**Comment by actionless** [comment]
also i found a usability issue with one of your proposals:

>>for this i don't know what should be the behavior when user selecting with keyboard or mouse the directory, not theme itself

>I imagined nothing will happen when user selecting the directories. See gtk3-demo's sidebar for example.

the current behavior when you open oomox app and navigating with keyboard `up`/`down` keys even if directory is not expanded the first theme is still visible and giving some idea of directory contents;

while with the new proposed behavior user will see nothing unless will expand the directory

**Comment by nana-4** [comment]
So sorry for the late response.

The new version looks pretty good. :) Great job, @actionless!

A few comments I noticed are:

- The [extra `6px` spaces around the panel](https://user-images.githubusercontent.com/9556384/48966524-91bf9a00-f016-11e8-88b0-1104d9b2a9eb.png) still remain. I suggest removing the spaces and adding `sidebar`+`left` style classes for **left panel** and `sidebar`+`right` style classes for **right panel** in order to add separators.

- There are [larger margins on the left of child items](https://user-images.githubusercontent.com/9556384/48966582-b405e780-f017-11e8-8371-628db1cad69b.png). I think it would look better if the margins are removed.



- Since "Import" button has been added, the headerbar looks even more crowded to me:
  ![image](https://user-images.githubusercontent.com/9556384/48966382-c4b45e80-f013-11e8-82aa-7bc06ec45247.png)

  To solve this issue, I'd still prefer to put the headerbar buttons inside the button menus (to be honest):
  ![image](https://user-images.githubusercontent.com/9556384/48966446-04c81100-f015-11e8-9ff5-2f589a1c3577.png)

**Comment by nana-4** [comment]
> while with the new proposed behavior user will see nothing unless will expand the directory
>
> the cool solution to this could be to show the preview of each (or first 5) theme under the directory (and don't show middle Edit section) when directory is focused; clicking on theme will choose that theme from the directory.

Sounds cool. Another solution I came up is to show a blank "welcome screen" something like this:

![image](https://user-images.githubusercontent.com/9556384/48967440-cb4ad200-f023-11e8-8f61-8dff1b05cee9.png)

This will be used for both directory selection and startup.
This solution is quite GNOME-ish and I don't know if you like it, though. ;)

**Comment by actionless** [comment]
1) 6px i'll fix, thanks! didn't knew about `sidebar+left`, could you give a link to some code usage example or doc/hig where it's mentioned?

2) for this i still prefer to collect more user feedback

3) yeah, it looks gnomish but it's not solving usability issue with previewing directory contents quickly without expanding subtree

**Comment by nana-4** [comment]
> 1. 6px i'll fix, thanks! didn't knew about sidebar+left, could you give a link to some code usage example or doc/hig where it's mentioned?

- [Adwaita, the default GTK+ theme](https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/theme/Adwaita/_common.scss#L3866-3885) has that style for quite a while.
- [GNOME HIG](https://developer.gnome.org/hig/stable/sidebar-lists.html.en)
- I didn't find good code usage example in actual apps so far, sorry. At least Nautilus and GtkFileChooserDialog have `sidebar` style class, though.

> 2. yeah, this child items margin i'll try to fix as well; could you please on the screenshot just move it to show me the expected result for that margin?

Maybe it would be good to reduce the margin about 10px.

**Before:** ![image](https://user-images.githubusercontent.com/9556384/48969920-e54adb80-f048-11e8-99de-cdcbde79a1eb.png) **After:** ![image](https://user-images.githubusercontent.com/9556384/48969926-ed0a8000-f048-11e8-853d-d5152c42181b.png)


> 4. directories: yeah, it looks gnomish but it's not solving usability issue with previewing directory contents quickly without expanding subtree

I just wondered if the users really want to preview the directory contents quickly, so I presented the another solution. But it does not mean to object to your solution. I'm OK with your solution. :)

**Comment by nana-4** [comment]
About the "Import" menu button: I'm rethinking about the style a bit. Maybe, just like [totem](https://gitlab.gnome.org/GNOME/totem/blob/master/src/totem-object.c#L3812), icon-button style with `list-add-symbolic` would look more neat than the current text-button style (on condition that there is no other button around the button).

![image](https://user-images.githubusercontent.com/9556384/48970179-b46ca580-f04c-11e8-8ea9-92132efdda41.png)

**Comment by actionless** [comment]
thanks! i'll try to implement both margin changes tonight/tomorrow

regarding previews it's actually the same point as about toolbars, if some UI change require additional mouse clicks or keyboard presses to get the same functionality as before i would think more about it

about import, if changing it to icon, i think more appropriate will be `->` (right arrow), because plus is usually used for "Create" or "New", not for "Open" or "Import"

**Comment by nana-4** [comment]
> about import, if changing it to icon, i think more appropriate will be -> (right arrow), because plus is usually used for "Create" or "New", not for "Open" or "Import"

Hm, I thought that "Import" is functionally closer to "Add" rather than "Open" in this case. Also `+` sign menu button is often used in GTK+ apps, so users can easily understand the button, I think.

**Comment by actionless** [comment]
i've reduced the paddings in UI

**Comment by actionless** [comment]
please add the remaining GUI improvements to this project, https://github.com/themix-project/oomox/projects/1 so we can discuss implementation of each separately

**Comment by actionless** [comment]
> Maybe it would be good to reduce the margin about 10px.

i've double-checked, it's not being set by oomox app, it's set in TreeView of the current GTK theme

**Comment by nana-4** [comment]
> please add the remaining GUI improvements to this project, https://github.com/themix-project/oomox/projects/1 so we can discuss implementation of each separately

Done! Sorry for being late. Please let me know if anything is missing.

> i've double-checked, it's not being set by oomox app, it's set in TreeView style of the current GTK theme

I see. Thanks for investigating it.

**Comment by actionless** [comment]
thanks a lot, i'll try to address few of them while i having holiday vacation now :)

**Comment by gsbhasin123** [comment]
Whoa @nana-4 this looks GREAT. I use Oomox for my own theme, https://gitlab.com/Gsbhasin84/materiav2, and such an improvement would surely be warmly welcomed by the community

**Comment by actionless** [comment]
> Done! Sorry for being late. 

thanks, closing this ticket then

> Please let me know if anything is missing.

mb a ticket about adding this view, but i still not sure if it's really needed

![](https://user-images.githubusercontent.com/9556384/48967440-cb4ad200-f023-11e8-8f61-8dff1b05cee9.png)

**Comment by nana-4** [comment]
> mb a ticket about adding this view, but i still not sure if it's really needed

I think it's fine without that :)
