### ISSUE TITLE
Change CSD window border / resize thickness?

### ISSUE THREAD

**Issue by geckolinux** [themix-project/oomox#170]
Hi there,

Thanks so much for oomox. I got my Numix-based theme almost perfect, but I can't figure out how to increase the border width on CSD windows to make them easier to resize. Any pointers? Possible to add this option to oomox?

Thanks a lot!

**Comment by actionless** [comment]
if it changes when you increase "Spacing" theme option?

**Comment by geckolinux** [comment]
Hi, thanks for the reply. "Spacing" appears to only change the height of the CSD top border (where the buttons are located).

**Comment by nana-4** [comment]
Window resize area can be expanded with [the margin](https://github.com/themix-project/oomox-gtk-theme/blob/9b6bc1762d11f3b2ba48136dc1e8ae59422f94e5/src/gtk-3.20/scss/widgets/_window.scss#L16-L17), without increasing the window border.

I've created a MR for this.

**Comment by geckolinux** [comment]
> The window resize area can be expanded with [the margin](https://github.com/themix-project/oomox-gtk-theme/blob/9b6bc1762d11f3b2ba48136dc1e8ae59422f94e5/src/gtk-3.20/scss/widgets/_window.scss#L16-L17), without increasing the window border.
> 
> I've created a PR for this.

Thanks a lot for the reply. Per your suggestion, I tried modifying `/usr/share/themes/my-oomox-theme/gtk-3.20/dist/gtk.css` and adding:

```````````````````
/**************
 ! Window frame
***************/
decoration {
  margin: 200;
````````````````````


But it doesn't seem to make any difference?

**Comment by nana-4** [comment]
@geckolinux If you want to add a quick fix locally, please try this:

```css
window decoration {
  margin: 16px;
}

.solid-csd window decoration {
  margin: 0;
}
```

**Comment by geckolinux** [comment]
> @geckolinux If you want to add a quick fix locally, please try this:
> 
> ```css
> window decoration {
>   margin: 16px;
> }
> 
> .solid-csd window decoration {
>   margin: 0;
> }
> ```

Thanks a lot for the tip. I tried putting it after the 
`````````
/**************
 ! Window frame
***************/ 
`````````

but it doesn't seem to make any difference. Where should I place that block of code?

**Comment by actionless** [comment]
try installing latest `oomox-git` from AUR, it already have integrated latest nana-4's changes

**Comment by nana-4** [comment]
> Where should I place that block of code?

Normally, oomox themes should be generated in `$HOME/.themes/my-oomox-theme/gtk-3.20/gtk.css`
So you should place it there.

> `/usr/share/themes/my-oomox-theme/gtk-3.20/dist/gtk.css`

That's strange. The CSS is in the wrong/invalid place.

Anyway, as @actionless says, it would be better to use the latest oomox.

**Comment by geckolinux** [comment]
> That's strange. The CSS is in the wrong/invalid place.

Ah, it's just that I manually moved it to /usr/share/themes because I use it globally for the root user account (when running programs with `kdesu` and/or `pkexec`.

> Anyway, as @actionless says, it would be better to use the latest oomox.

OK, I'll try that. Can I import my custom oomox theme into the new version somehow?

**Comment by nana-4** [comment]
> it's just that I manually moved it to `/usr/share/themes`

Ah, I mean it is strange that the CSS is in `dist/`. (But `oomox-gtk-theme` seems to create the `dist/` directory...)

So you can add that block of code in `/usr/share/themes/my-oomox-theme/gtk-3.20/gtk.css` instead of `/usr/share/themes/my-oomox-theme/gtk-3.20/dist/gtk.css`.

> Can I import my custom oomox theme into the new version somehow?

Your custom oomox style is in `~/.config/oomox/colors`. So you just need to copy it.

**Comment by nana-4** [comment]
@actionless IMO, `oomox-gtk-theme` shouldn't create `dist/` and `gtk.gresource.xml` in `gtk-3.0` and `gtk-3.20`. Can you fix it?

**Comment by actionless** [comment]
the thing with dist indeed looks weird, i'll have a look into it

but what's wrong with gresource?

**Comment by actionless** [comment]
hm, i've got the point of that dist dir -- since real css is mentioned in gresource.xml, it's being compiled into gresource so the final gtk.css is only loading pre-compiled gresource (which should make opening gtk3 apps slightly faster)

i think the real thing which should be fixed regarding gresource/dist is renaming resource path accordingly to the name of the theme (now it's always hardcoded to `/org/numixproject/gtk-VERSION`)

**Comment by actionless** [comment]
> Can I import my custom oomox theme into the new version somehow?

it should remain in `~/.config/oomox/colors` after update, so all you need is just to `Export` that theme in oomox app again

**Comment by nana-4** [comment]
> but what's wrong with gresource?

Actually both `dist/` and `gtk.gresource.xml` don't cause problems, but they are simply unnecessary in the generated themes. IIRC, they are used only when generating the `gtk.gresource`.

See the upstream Numix. It doesn't have `dist/` and `gtk.gresource.xml` in the generated theme.

> renaming resource path accordingly to the name of the theme (now it's always hardcoded to /org/numixproject/gtk-VERSION though it still working somehow even if there are more than one theme with that path)

Indeed. I agree with that.

**Comment by actionless** [comment]
ah, my bad, i didn't understood your point first time, so you suggesting to leave only built gresource without `xml` and `dist`?
