### ISSUE TITLE
mpv titlebar doesn't follow oomox colors.

### ISSUE THREAD

**Issue by lb-d** [themix-project/oomox#175]
I can't seem to find the color setting in the css files rendered either, and I set all colors for all widget sets. Dunno how this works exactly.

Intended color:  https://i.imgur.com/QQElHDW.png

what mpv looks like:  https://i.imgur.com/x0y3ltV.png

I fixed it for now by hiding mpv decorations by adding "no-border" to .config/mpv/mpv.conf   but would be nice to know how to change it if I want to post themes online.

**Comment by actionless** [comment]
mpv doesn't have any theme since it's not using any graphical toolkit

you have some troubles with your gnome not applying themes correctly, try restarting it or so

**Comment by nana-4** [comment]
As a supplement: mpv uses SSD titlebar on gnome-shell. The SSD titlebar is actually rendered by gtk theme (and mutter), but sometimes you need to restart gnome-shell to see the titlebar theme changes.

Without rebooting, you can restart gnome-shell by pressing <kbd>Alt</kbd>+<kbd>F2</kbd> and typing `r` (if you are on "GNOME on Xorg" session).

**Comment by lb-d** [comment]
That was easy. Thanks guys.
