### ISSUE TITLE
requiring super user permission to launch oomox-gui

### ISSUE THREAD

**Issue by as3mbus** [themix-project/oomox#179]
so i just installed oomox at arch through the following AUR repo 
https://aur.archlinux.org/packages/oomox/

I used makepkg method to install the package. it all went well 
but after installation i cant launch oomox through application launcher (rofi in my case) and running oomox-gui through terminal require super user permission. 
does it really necessary to do so ?

**Comment by actionless** [comment]
>  and running oomox-gui through terminal require super user permission.

what do you mean?

**Comment by as3mbus** [comment]
![image](https://user-images.githubusercontent.com/16043293/49786389-284dc400-fd56-11e8-9037-1cdd448a65b6.png)
i need sudo to run the command properly

**Comment by actionless** [comment]
it seems like for some reason on your system that file don't have `o+x` permission, start from `ls -l /opt/oomox/gui.sh`

**Comment by as3mbus** [comment]
![image](https://user-images.githubusercontent.com/16043293/49847241-b03cd800-fe01-11e8-8329-fb5a58175e1b.png)
yeah it doesnt. is it caused by installing it through makepkg
i did install this months ago which might be a reason

**Comment by actionless** [comment]
i think you have some specific default permissions in your filesystem, i think that could be fixed by setting `a+x` permission to executables inside install script, i'll fix it in few minutes and let you know

**Comment by actionless** [comment]
try installing `oomox-git` aur package now

**Comment by actionless** [comment]
@as3mbus ping
