### ISSUE TITLE
Improve Materia theme color options

### ISSUE THREAD

**Issue by nana-4** [themix-project/oomox#182]
As we discussed at https://github.com/nana-4/materia-theme/pull/329, Materia theme color options should have room for improvement.

Here's the list of _desirable_ description/order of Materia color options:

- [x] `Background`
- [x] `Text` (current name: `Foreground/text`)
- [x] `Surface (e.g. Button, Menu, Popover)` (current name: `Button background`)
- [x] `View` (current name: `Textbox background`)
- [x] `Headerbar Background` (current name: `Menu/toolbar background`)
- [x] `Headerbar Text` (current name: `Menu/toolbar text`)
- [ ] ? `Error`
- [ ] `Accent` (current name: `Selection highlight`)
- [x] `Selection Opacity`
- [x] `Translucent Panel Opacity` (current name: `(Gnome Shell) Panel opacity`)

*Feel free to edit as needed.*

**Comment by nana-4** [comment]
I renamed `Titleber` to `Headerbar` because the preview in GUI has a headerbar, not titlebar.

**Comment by actionless** [comment]
i suggest leaving Foreground/text as is (for having at least minimal compatibility on BG and FG with other theme styles)

with the rest all i agree and going to implement soon

**Comment by actionless** [comment]
so my idea to define it like that:

Common:
- [x] BG `Background`
- [x] FG `Text` (current name: `Foreground/text`)

Materia-specific:
- [ ] MATERIA_SURFACE `Surface (e.g. Button, Menu, Popover)` (current name: `Button background`)
- [ ] MATERIA_VIEW `View` (current name: `Textbox background`)
- [ ] MATERIA_HEADER_BG `Headerbar Background` (current name: `Menu/toolbar background`)
- [ ] MATERIA_HEADER_FG `Headerbar Text` (current name: `Menu/toolbar text`)
- [ ] MATERIA_ACCENT `Accent` (current name: `Selection highlight`)  (or use common ACCENT_BG? i am not sure here)
- [x] MATERIA_SELECTION_OPACITY `Selection Opacity`
- [ ] MATERIA_PANEL_OPACITY `Translucent Panel Opacity` (current name: `(Gnome Shell) Panel opacity`)

This won't be addressed in this iteration, sorry:
- [ ] ? `Error`

**Comment by actionless** [comment]
or mb i should refactor the app to allow multiple options with the same keys (and make them synchronized when change)

**Comment by nana-4** [comment]
Thanks for the clarification! Both approaches are attractive and gave me more ideas.

As a compromise plan, how about these?

- Rename the description `Foreground/text` to `Text` for **all themes** (but leave the var name as `FG`). Pros:
  - It sounds more consistent since other existing descriptions use `text`, but not `foreground`. (e.g. `Selection text`, `Button text`, etc.)
  - It can avoid the potential semantic conflict between `Foreground` and `Surface` in Materia.
- Rename the var names `MENU_BG` & `MENU_FG` to `HDR_BG` & `HDR_FG` (and use them for **all themes** including Materia). Reasons:
  - In Arc and Materia, those vars don't change the **menu** background/text.
  - But in all 3 themes, those vars change the **headerbar** background/text.
  - Those var names should sound more consistent with `HDR_BTN_BG` & `HDR_BTN_FG`. 
  - (This requires the refactoring, but) it would be nice if the description also changed to:
    - `Headerbar/Menu Foo` in Numix-based.
    - `Headerbar Foo` in Arc and Materia.

---

I'm not very sure about `MATERIA_VIEW` and `MATERIA_ACCENT` so far, but:

> MATERIA_ACCENT `Accent` (current name: `Selection highlight`) (or use common ACCENT_BG? i am not sure here)

IMHO, using `SEL_BG` as fallback value seems to be better, because I think:
- `SEL_BG` can be paraphrased to "Primary accent color".
- `ACCENT_BG` can be paraphrased to "Secondary accent color".

and Materia won't have secondary accent color.

---

In any case, having `MATERIA_SURFACE` (or just `SURFACE`?) var seems very nice to me, especially when using CUI. Using `BTN_BG` for surface color is misleading atm (in Materia).

**Comment by actionless** [comment]
thanks! i'll do some changes based on your latest comment and let you know here

**Comment by actionless** [comment]
> SEL_BG can be paraphrased to "Primary accent color".

this not gonna work fine for themes which have SEL_FG

**Comment by nana-4** [comment]
> thanks! i'll do some changes based on your latest comment and let you know here

Great, thanks!

> this not gonna work fine for themes which have SEL_FG

I mean, most themes use a colorful (high saturation) color for selected_bg_color, so `SEL_BG` looks like an accent color.

For example, "Halloween" preset have pumpkin-orange (primary accent) and purple (secondary accent). In Halloween preset, I think Materia should have pumpkin-orange, not purple, as an accent color.

**Comment by actionless** [comment]
i mean pair Selection highlight/Selection text sounds organic, but i can't imagine how to name well SEL_FG if SEL_BG will be named "Primary cccent color"

**Comment by actionless** [comment]
please check now with the `oomox-git` from AUR (or i can upload ubuntu package if you're using it on your main machine)

**Comment by nana-4** [comment]
Excellent work!

Some nitpicking:

- Is the display name `Header` intentional? I think `Headerbar` sounds more obvious.
- The display name `DE Panel opacity` might cause misunderstanding as if it can change the opacity even a solid background panel. What about renaming it to `Translucent Panel Opacity` or something else?

  For example, on MATE and Unity, panel background is always **solid**:
  ![image](https://user-images.githubusercontent.com/9556384/50370469-a88fe700-05ea-11e9-9098-939ae6ce3cb3.png)

  On GNOME Shell and Budgie, panel background can be dynamically changed:
  ![peek 2018-12-22 12-51](https://user-images.githubusercontent.com/9556384/50370357-6c5b8700-05e8-11e9-9d8e-cfc5d28f109a.gif)

**Comment by actionless** [comment]
1) header i thought would be more abstract (since it's used not only for headerbars)
2) it just sounds too weird to me since both words translucent and opaque are describing the same quality of an object

**Comment by nana-4** [comment]
Understood. I don't have strong opinions on that, so I'm OK with that.

> btw, mb you would also like to re-design Christmas theme to look better? i thought what now during the holidays it would be nice to have a seasonal theme at first place when opening the app

Sounds interesting.

If I have some opinion on the current Christmas theme, it looks too dark to me :)
(Honesty, in my first impression it looked like a Black Metal Christmas 😈🤘🎅)

How about something like this?

![image](https://user-images.githubusercontent.com/9556384/50380470-87db9600-06ab-11e9-944a-fbc5d95fa649.png)


Here's the concept of colors:

- Snow White = backgrounds
- Santa Claus Red = header
- Christmas Tree Green = selection

if that's alright, I'll send a PR.

**Comment by actionless** [comment]
yup, looks much better, i was just using Import->From image from this one:

**Comment by actionless** [comment]
the latest flatpak build is finally working btw :fireworks:

**Comment by AryToNeX** [comment]
Hi, I was just passing by and wanted to ask you if you can make a "counter" background color option for apps on Plank Dock (eg. Telegram Desktop and Psensor).

![photo](https://user-images.githubusercontent.com/13177694/50978105-fdd95d00-14f3-11e9-914a-99044ffff30b.png)

**Comment by actionless** [comment]
@AryToNeX create a separate issue in the Materia repo

**Comment by AryToNeX** [comment]
@actionless even if this has more to do with oomox than Materia? That color is red (and looks fine) if I use the normal uncustomized Materia theme

**Comment by actionless** [comment]
how it's related to the _GUI_ app for designing themes?

**Comment by actionless** [comment]
@nana-4 is there still anything left to be done for this one?

**Comment by nana-4** [comment]
@actionless Looks OK-ish enough. Let's close this. Thanks a lot for your hard work!
