### ISSUE TITLE
Add "Keyboard Shortcuts" and "About Themix" items into the primary menu

### ISSUE THREAD

**Issue by nana-4** [themix-project/oomox#186]

**Comment by actionless** [comment]
added "Keyboard Shortcuts"

**Comment by actionless** [comment]
could you please provide a mockup for the "About Themix" window?

**Comment by nana-4** [comment]
How about simply imitating Nautilus, etc.? Most modern GNOME/GTK apps have this pattern.

![image](https://user-images.githubusercontent.com/9556384/50733314-b50d6580-11ce-11e9-8889-c00a1ea0478e.png)
![image](https://user-images.githubusercontent.com/9556384/50733316-c8203580-11ce-11e9-82f4-88e1d8148c7d.png)

**Comment by nana-4** [comment]
OK. In the GNOME's latest mockup of [about-dialogs](https://gitlab.gnome.org/Teams/Design/os-mockups/blob/master/about-dialogs/about-dialogs.png), there is the "Legal" tab. Maybe we can imitate that. 

How about renaming "Legal" to "Plugins" and adding version info next to the name of each plugin?

**Comment by actionless** [comment]
yes, that's looking similar to what i had on my mind :+1:

**Comment by actionless** [comment]
btw good idea with the buttons

also speaking of translations, mb later i can setup integration with transifex so users could easier edit .po files

**Comment by actionless** [comment]
what about adding third menu item "Tutorial" and show it on the first run?

**Comment by actionless** [comment]
yeah, Help sounds like a more general name than Tutorial

>  but I don't know what kind of design/info it should be.

i myself don't know what could be not clear in the app so it require some help, but i guess to make just few buttons:

 - how to create and export theme
 - how to import and export base16
 - how to create themes from images
etc

and when clicking on each, it either opens wiki/md from the repo, in a way like this doc https://gist.github.com/actionless/f9ad9e5ab9eac414dac8a3392beb3ad5

or just shows some help message inline


idk

**Comment by actionless** [comment]
i don't like idea of straightly opening web page -- i think it could alienate from reading the help in a way, so i thought what displaying links to some particular help topics could be useful right in the help window

or, mb, more precise names for such window could be "Getting started…"

**Comment by nana-4** [comment]
> "oh instead of doing real help they just put a link to 100 pages of wiki, so i'll just close it instead of reading'

Even though I pointed to Builder as an example, but in Themix, I think having only several sub-pages on top page of wiki is enough.

Anyway I share my idea of a startup/help dialog something like this:

```
                    Welcome to Themix                                <-- title

  Are you new to Themix? Online documentation is available!

  [ How to create and export theme ]                                 <-- link button
  [ How to import and export base16 ]                                <-- link button
  [ How to create themes from images ]                               <-- link button

  [x] Don't show show this dialog at startup.                        <-- checkbox

----------------------------------------------------------
                            OK                                       <-- button
```

**Comment by actionless** [comment]
hi, @nana-4, have you got any luck with the mascot? i thought it would be cool to use it for "About" window

**Comment by nana-4** [comment]
Sorry, I'm not an illustrator, so I don't have an ability to create a nice looking mascot. I can only create a terrible looking mascot :P I’m afraid having a bad looking mascot can give users a bad impression...

Besides, I'm still not a fan of the idea of having a mascot,  to be honest -- the concept of "mascot for application" reminds me of ancient applications... I think having a simple character/mascot in the app icon, like Firefox and Xfce, is not too bad, but I don't have a good idea to make it look decent at the moment.

> i thought it would be cool to use it for "About" window

Most GTK apps show their own icon in the About dialog. Shouldn't we follow that for now?

**Comment by actionless** [comment]
but we'll loose the possibility to be in SuperTuxCart at some point!

**Comment by nana-4** [comment]
lol. Then the mascot needs a body as well as a head ;)

By the way, how about such a "colorful robot" instead of an "alien"?

![image](https://user-images.githubusercontent.com/9556384/94356006-7b783e80-00c4-11eb-8ce1-b7edeea48f41.png)


The robot implies it's recolorable, transformable and replicable...

**Comment by actionless** [comment]
that actually nice, would be very hard for you to get along now as not having a drawing ability :)

what about trying suiseiseki-like colors for the eyes? or that might look as a reference to 3d-glasses? :(

> re: body
in worst case we could just mount a head on top of a square-wheel bicycle

**Comment by actionless** [comment]
i've actually right now realized what this concept of robot could be very organically variated for different contexts:

for example:
by adding star-like glasses it could be used as a headline for Pop Art theme section
by adding a red hat on robot's had - as a headline for Gnome section
by pixelating and changing rainbow into CGA - as a headline image for Retro section

and etc

**Comment by nana-4** [comment]
> that actually nice, would be very hard for you now to pretend not having a drawing ability :)

I found it quite difficult for me to draw the alien. But a robot is much easier to draw even with my poor skills :)

> what about trying suiseiseki-like colors for the eyes?

IMO, having different colored eyes on colorful skin could be _information overload_ (or it would look like a "broken" robot).

About adding different variations of robot to each section: If this were a game app, I'd have no objection. But I'm not sure if it works well with this app -- isn't it too pop as a utility tool?

**Comment by actionless** [comment]
those were just usage examples of variability, but generally it could any other example of variable logo usages -- like matching it to release codename, or using on a website sections, etc. doesn't mean what any of those gonna happen but just nice to be able to have that variability potential there :)

**Comment by actionless** [comment]
finally implemented both Hotkeys and About windows
