### ISSUE TITLE
Capitalize words based on GNOME HIG

### ISSUE THREAD

**Issue by nana-4** [themix-project/oomox#191]
See "Capitalization" in https://developer.gnome.org/hig/stable/writing-style.html.en

@actionless Do you agree with this? (e.g. "Theme style" -> "Theme Style") If you agree, should I send a PR for this?

**Comment by actionless** [comment]
yes, thanks in advance!

**Comment by nana-4** [comment]
In HIG, "Sentence capitalization" is used for checkbox and radio labels, since these labels are usually sentences.

I think Oomox's row label is rather closer to "Header" than "Sentence".

**Comment by actionless** [comment]
headers in theme models are typed as `separator` (it indeed could make sense to make it more semantically correct and name them `header` or `headline`)

**Comment by actionless** [comment]
here's more stripped down example from transmission to show what i mean:

![2018-12-24--1545630311_621x106_scrot](https://user-images.githubusercontent.com/1655669/50391621-83fd5180-0747-11e9-9b55-c360ca7f0609.png)

**Comment by nana-4** [comment]
Hmm, in GNOME Settings, "Header capitalization" is adapted to the row labels basically.

![image](https://user-images.githubusercontent.com/9556384/50391656-f04d7480-078a-11e9-9f40-649148687645.png)

Another example from GNOME's mockup: https://gitlab.gnome.org/Teams/Design/app-mockups/blob/master/tweaks/tweaks-wires.png

**Comment by actionless** [comment]
i've also capitalized few more labels and replaced `e.g.` which wasn't recommended to use in HIG

**Comment by actionless** [comment]
i did few more writing style and typography improvements, please install the latest oomox-git and check if it's all done

**Comment by nana-4** [comment]
Looks much better! Nice job!

A few things I noticed:

1. I've never seen the ellipsis (…) used for **buttons** in other GTK apps, so it looks a bit odd to me. Can't we remove the ellipsis from the buttons?

1. I think it would look better to use `:` instead of `()` for DE/GTK name.
  For example: `(GTK3)` -> `GTK3:`, `(Cinnamon)` -> `Cinnamon:`

1. I noticed that only "Accent Color" contains the word "Color" at the end. What about removing `Color`, or alternatively, renaming `Accent Color (Checkboxes, Radios)` to `Selection Controls`?

1. Instead of a line break, how about using a smaller font size for the theme descriptions `GTK2, GTK3, Qt5ct, Cinnamon, [...]` like [my mockup](https://user-images.githubusercontent.com/9556384/46919705-07027d00-d01e-11e8-9866-ba4b78e2cf03.png)?

**Comment by actionless** [comment]
1) in HIG it's written it should be if they open some dialog (except for Preferences)
2) ok
3) i think i can rename Selection Highlight to Selection Color for the consistency
4) i think splitting it into toolkits and DE/WM's makes it easier to read

**Comment by actionless** [comment]
2) i've tried removing brackets and it doesn't look well, mb in GTK+3 there is some widget or style similar to "Badge" for such case?

**Comment by actionless** [comment]
2) attempted to fix this
3) and this

**Comment by actionless** [comment]
1) i temporarily commented out ellipsis-es on button for the latest release (also released it on flatpak) until it will be clarified more

**Comment by nana-4** [comment]
So sorry for the late reply. I checked the current status now.

1. I re-checked HIG, and it seems you are right; [HIG recommends using ellipses for buttons as well.](https://developer.gnome.org/hig/stable/buttons.html.en#text-buttons) (Personally I still feel a bit strange that the headerbar buttons have ellipses, though. However, [if they become popover menu-items](https://github.com/themix-project/oomox/issues/185#issuecomment-449665411), they'd look normal in my opinion.)
2. Please see below.
3. For consistency with "Selection Text", I think "Selection Background" is better than "Selection Color".
4. OK. (I still prefer my proposal one, but it's okay as it's not a big matter.)

Regarding 2:

I am sorry, but to be honest, I prefer the previous style of only the "Theme Options" section (for consistency with other themes). It was easier to see to me. Also IMO, "Primary Caret" and "Secondary Caret" should be in the top "Theme Colors" section. However, if you prefer the current style, I won't be against it.

> i've tried removing brackets and it doesn't look well

Maybe if there are separators between rows, it may look better, I guess.

> mb in GTK+3 there is some widget or style similar to "Badge" for such case?

AFAIK, there is no useful widget or style for such case, unfortunately.

**Comment by actionless** [comment]
@nana-4  so, can this one be closed or more capitalization / text stuff remains?

**Comment by nana-4** [comment]
Sorry, I forgot to reply this:

> 3. It's not always background.

But it's also not always "Selection", isn't it? (e.g. progress bar)

For the sake of consistency, personally I prefer:
- `Selected Background` than `Selection Color`
- `Selected Text` than `Selection Text`
- `Selection controls (Checkbox, Radio)` than `Accent Color (Checkboxes, Radios)`

But this is a relatively trivial thing, so if it doesn't fit your taste, please go ahead and let's close this issue.

**Comment by actionless** [comment]
selected_bg / fg naming is sorta for uniformity with gtk2 and gtk3 themes there those are standard naming

while, of course, in UI there is no need to follow that technical side


> Selected Background than Selection Color
> Selected Text than Selection Text

those minor renaming i don't mind at all


> Selection controls (Checkbox, Radio) than Accent Color (Checkboxes, Radios)

this could be quite misleading because under the hood theme var is called ACCENT

**Comment by nana-4** [comment]
> those minor renaming i don't mind at all

:+1: 

> this could be quite misleading because under the hood theme var is called ACCENT

Indeed. Regarding that, I take it back.
