### ISSUE TITLE
resvg-git dependency fails to build on Arch

### ISSUE THREAD

**Issue by stevensonmt** [themix-project/oomox#195]
```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> usvg/src/convert/marker.rs:74:67
   |
74 |                 svgdom::AngleUnit::Radians => angle.num * 180.0 / std::f64::consts::PI,
   |                                                                   ^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> usvg/src/tree/mod.rs:251:23
    |
251 |     let mut decoder = libflate::gzip::Decoder::new(inner).map_err(|_| Error::MalformedGZip)?;
    |                       ^^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `usvg`.
```

**Comment by actionless** [comment]
and why you reporting it here instead of resvg?

**Comment by stevensonmt** [comment]
Because 4 days ago this project changed its dependency to resvg https://github.com/themix-project/oomox/releases/tag/1.8.0
>Notable changes:
> 2018-12-22 3941b405 actionless chore(packaging: arch): use resvg-git instead of inkscape

When that dependency fails it is a breaking change for this project. I am happy to report it upstream as well, but I thought it worthwhile to know that the recent change was breaking.

**Comment by actionless** [comment]
it's a dev package, for stable release please use https://aur.archlinux.org/packages/oomox
