### ISSUE TITLE
change_color.sh: No such file or directory

### ISSUE THREAD

**Issue by mvrozanti** [themix-project/oomox#196]
Upon exporting theme I get

`bash: /home/nexor/util/oomox/plugins/theme_oomox/gtk-theme/change_color.sh: No such file or directory`

I'm on Arch Linux

**Comment by mvrozanti** [comment]
Whoops I missed the `--recursive` upon cloning. 

```
git submodule init 
git submodule update
```

Fixed it

Happy new year's!

**Comment by actionless** [comment]
hi, on arch linux you can just install from AUR
