### ISSUE TITLE
CentOS compatibility broken with version 1.10

### ISSUE THREAD

**Issue by LaurentTreguier** [themix-project/oomox#198]
Since version 1.10, the Python byte compilation step fails on CentOS when building oomox.
Extract from [the very end of the build log](https://copr-be.cloud.fedoraproject.org/results/tcg/themes/epel-7-x86_64/00841647-oomox/builder-live.log):
```py
*** Error compiling '/builddir/build/BUILDROOT/oomox-1.10-2.el7.x86_64/opt/oomox/oomox_gui/helpers.py'...
  File "/opt/oomox/oomox_gui/helpers.py", line 47
    return func(*computed_args, *rest_args)
                                ^
SyntaxError: invalid syntax
```
The CentOS containers used for building provide Python 3.4; so I suspect this is a newer syntax from Python 3.5 or 3.6 that's used here (I don't know Python very well).
Oddly enough, this line was there before version 1.10, but didn't trigger any error, I don't understand why it only does so now.

**Comment by actionless** [comment]
but which gtk3 version is used in that centos version which is using python3.4?

**Comment by LaurentTreguier** [comment]
GTK 3.22 is used

**Comment by actionless** [comment]
last time when i was trying to locate any system using python3.4 and gtk 3.18+ i found only some old version of openmandriva, could you please create a dockerfile for affected centos version? 

https://github.com/themix-project/oomox/tree/master/dockerfiles

**Comment by LaurentTreguier** [comment]
Here is a dockerfile pieced together from the others:
```dockerfile
FROM library/centos:7
WORKDIR /opt/oomox-build/

# App and test (xvfb, pylint) deps
RUN yum-config-manager --enable extras && \
    yum install -y epel-release
RUN yum upgrade -y && \
    yum install -y gtk3 xorg-x11-server-Xvfb psmisc gnome-tweak-tool \
        python34-pip python34-gobject python34-PyYAML
RUN pip3 install setuptools && \
    pip3 install pylint

COPY . /opt/oomox-build/
```
I'm not sure about the dependencies though; I don't know exactly which ones are necessary in the dockerfiles

**Comment by actionless** [comment]
thanks, let's see if it's working on travis

**Comment by actionless** [comment]
the build started: https://travis-ci.org/themix-project/oomox/builds/475410584

**Comment by actionless** [comment]
hm, actually pylint is fine with it python3.4, weird:

https://travis-ci.org/themix-project/oomox/jobs/475414225

**Comment by LaurentTreguier** [comment]
I'll try to pinpoint which commit exactly introduced the problem for me, maybe this could help

**Comment by LaurentTreguier** [comment]
That seems to do the trick, it works fine again with this commit :+1:

**Comment by actionless** [comment]
however, now i am wondering, how could i reproduce the failure to include it to the tests

mb you could add that bytecompile command to the end of docker file?

**Comment by actionless** [comment]
(so dockerfile will fail to build if that command will fail)

**Comment by actionless** [comment]
and to test what dockerfile is actually breaking, you could partially revert the patch for this line:

`func(*computed_args, *rest_args)`

**Comment by actionless** [comment]
because if pylint is not catching that error i couldn't otherwise guarantee what it won't break again

**Comment by actionless** [comment]
oh, more good news for today :D 

resvg 0.5 (with fixes needed for oomox) just released!
https://github.com/RazrFalcon/resvg/releases/tag/v0.5.0

so when this aur package will update to 0.5 it can be used as dependency of oomox:
https://aur.archlinux.org/packages/resvg/

however Arc theme haven't yet merged `resvg` branch, so dependency on both `resvg` and `inkscape` should stay til then: https://github.com/NicoHood/arc-theme/pull/177

**Comment by actionless** [comment]
in the meantime, try packaging resvg on your fedora build system (if nobody did that already)

it should be quite easy, see flatpak build scenario as a reference: https://github.com/themix-project/oomox/blob/master/packaging/flatpak/com.github.themix_project.Oomox.json#L31-L56

**Comment by actionless** [comment]
good, i found a working testcase for python 3.4 problem:

```

(env34)
   lie  /home/lie/projects/oomox  master (4/44)  
$ python3 -O -m compileall ./oomox_gui/ ./plugins/*/oomox_plugin.py  | grep -v -e '^Listing'
Compiling './oomox_gui/helpers.py'...
***   File "./oomox_gui/helpers.py", line 50
    return func(*computed_args, *rest_args)
                                ^
SyntaxError: invalid syntax
```
