### ISSUE TITLE
Get black background color in gtk3 apps

### ISSUE THREAD

**Issue by nabil48** [themix-project/oomox#200]
I was try create colorscheme for gtk3, gtk2 and qt5ct aplication on my i3-gaps. but in gtk3 aplication get black background. I use  lxappearance for gtk3 theme management.
__sorry if my english language to bad__

![screenshot_20190112_095632](https://user-images.githubusercontent.com/37516576/51072818-f5228b80-1699-11e9-8c7f-f5a50b120a09.png)

**Comment by actionless** [comment]
i am not sure i understand your question right but on the screenshot i see what `Textbox Background` and `Textbox Text` are set to almost the same value

**Comment by actionless** [comment]
also you could find already pre-made gruvox themes under Plugins -> Base16 -> gruvbox
