### ISSUE TITLE
Materia Dark selection opactiy

### ISSUE THREAD

**Issue by duhok1** [themix-project/oomox#201]
On some GTK windows (in example below, Dropbox upload window) the selected text is less readable (see left), while the normal behavior (right side) is as desired.

This is using Modern: Materia-Dark and latest Oomox git version.
![img01](https://user-images.githubusercontent.com/46654846/51089340-90b70900-1739-11e9-9dfb-a4ac10f1d422.png)

**Comment by actionless** [comment]
create ticket in Materia repo
