### ISSUE TITLE
Support for KDE themes

### ISSUE THREAD

**Issue by gerardlouw** [themix-project/oomox#203]
Materia and Arc themes both have popular and well-maintained KDE variants:
* https://github.com/PapirusDevelopmentTeam/materia-kde
* https://github.com/PapirusDevelopmentTeam/arc-kde

For consistency between GTK and Qt applications on all desktop environments, it would be useful to have support for modifying the Kvantum themes exported by these projects. Additionally for KDE users, it would be great if at least the Aurorae themes (window decorations) were supported as well. Konsole and Plasma colour scheme support would be nice as well, but these are easy enough to configure by hand.

The colors are all SVG/config file based so it should be fairly straightforward.

**Comment by actionless** [comment]
you should create that ticket in those repos accordingly:

all other parts of Materia and Arc themes (gtk, gnome, xfce, whatever) are support change-color.sh script in the root of their repo

when those kde themes there designed their author ignored that so they are not compatible with the rest of Arc/Materia themes in terms of color-changing
