### ISSUE TITLE
[Materia]Theme doesn't load in some apps if the background color is flesh-like

### ISSUE THREAD

**Issue by kvnbai** [themix-project/oomox#210]
The theme is not loading in some applications (e.g. Nautilus, Oomox) if I am using this background color (#D6C4A0) or flesh-like colors such as these (e.g. #A89267, #C8AC72).

**Theme Style:** Materia
**Background:** #D6C4A0
**Text:** #060D29
**Header Background:** #060D29
**Header Text:** #D6C4A0
**Selection Color:** #A89267
**View:** #D6C4A0
**Surface:** #A89267

**Comment by actionless** [comment]
please create your issue in materia repo
