### ISSUE TITLE
Oomox still downloads the old version of icons theme

### ISSUE THREAD

**Issue by gusbemacbe** [themix-project/oomox#212]
Hi @actionless and @SmartFinn !

I upgraded my icons theme in the branch `master`. And I also upgraded your repository, but it downloaded the old version of my icons theme. I suggest your repository check if there is a new version or a new update, it will download the latest version.

**Comment by actionless** [comment]
that's a matter of packaging, not of the app itself

you can also find more info on topic by reading about "git submodule"s

indeed during building oomox-git package it's possible inside package buildscript to just pull the latest master from each submodule, but practice already shown what themes tend to break some some compatibility during their development, so usually it's better to check what it at least still generating the right theme before updating submodule to a newer version

for stable packages there is different strategy: they're not relying on submodules of oomox repo but on tags of theme/icon plugins themeselves

cc @LaurentTreguier if you have something more to add to this

**Comment by LaurentTreguier** [comment]
I'm thinking of something now. Some of the themes used in plugins are packaged in distributions already.
Why not add them as dependencies to the packages, and symlink them inside of Oomox's plugin directories ? Would that work ?

**Comment by actionless** [comment]
no, because what is packaged in distros -- is already built theme, not theme sources

**Comment by actionless** [comment]
should this we closed?

**Comment by gusbemacbe** [comment]
Yes, @actionless.
