### ISSUE TITLE
Oomox is not in another language

### ISSUE THREAD

**Issue by gusbemacbe** [themix-project/oomox#216]
Hello @actionless !

I switched my GUI to Portuguese and open Oomox, it is still in English.

I also tried to run `LC_ALL=pt_PT.UTF-8 oomox-gui`, `LANG=pt_PT.UTF-8 oomox-gui`, `LANG_ALL=pt_PT.UTF-8 oomox-gui`,`LC_ALL=pt_PT oomox-gui`, `LANG=pt_PT oomox-gui` and `LANG_ALL=pt_PT oomox-gui`. Nothing worked.

**Comment by actionless** [comment]
thanks for your report!
i've fixed the makefile: e20618094b11c7c80a8be4beff9296c76986c9e4

**Comment by actionless** [comment]
i also found and fixed some previously untranslatable strings in plugin for importing colors from images

**Comment by gusbemacbe** [comment]
I was going to report it.

**Comment by gusbemacbe** [comment]
Only `LC_ALL=pt_PT oomox-gui` worked, but `LC_ALL=fr oomox-gui` and `LC_ALL=pt_BR oomox-gui` do not work.

**Comment by actionless** [comment]
try setting `LANGUAGE` env var instead

**Comment by gusbemacbe** [comment]
Hi @actionless !

There are few untranslated strings (ones 6) in all languages, expect French.

French is totally outdated and there are many and many missed strings. I will upgrade French translation, copying the upgraded Dutch translation file.
