### ISSUE TITLE
new version oomox update errors

### ISSUE THREAD

**Issue by medioman** [themix-project/oomox#230]
sorry my errors,delete this post please.
sorry

**Comment by gusbemacbe** [comment]
Ciao @medioman, non utilizzare Yaourt, utilizza il Yay.

**Comment by actionless** [comment]
also in readme it's recommended `pikaur`: https://github.com/themix-project/oomox#install

**Comment by medioman** [comment]
Thank sorry for the errors the post.

Best regardsEctor


  ----Messaggio originale----
 
 Da: notifications@github.com
 
 Data: 4-mar-2019 16.38
 
 A: "themix-project/oomox"<oomox@noreply.github.com>
 
 Cc: "medioman"<sonbello@alice.it>, "Mention"<mention@noreply.github.com>
 
 Ogg: Re: [themix-project/oomox] new version oomox update errors (#230)
 

 

 
also in readme it's recommended pikaur: https://github.com/themix-project/oomox#install
