### ISSUE TITLE
[Feature Request] Suru++ Asprómauros support

### ISSUE THREAD

**Issue by gusbemacbe** [themix-project/oomox#232]
Hello @actionless !

I duplicated Archdroid and Suru++, but they did not work because I removed the part of colourful folders, and Oomox failed to load, and I duplicated Archdroid, and the plugin failed to load and to recognise the templates. 

[Suru++ Asprómauros](https://github.com/gusbemacbe/suru-plus-aspromauros) is based on [Suru++ 25 Dark](https://github.com/gusbemacbe/suru-plus-dark), but fully monochromatic, like Archdroid. 

I think we need to add tutorials to WIki, because at OpenDesktop, a user asked me how to import icons themes that do not have plugin, for example, Suru++ Asprómauros and Suru++ Dark, and where the exported icons themes are exported. Sorry for his inexpertness in Oomox! I wanted to help him.

**Comment by actionless** [comment]
you need to create a new themix-plugin for new icons:

currently change_color.sh script (which have old knowledge of how colors in icontheme should be replaced)

so there are two ways to address the thing below:

1) move change_color.sh to icon theme itself, so themix-plugin will be just calling change_color.sh script so have less knowledge and it will be easier to just replace icon directory to another one also with change_color.sh script in the root

2) just write a new themix-plugin for new icons, it's basically just copying some of existing plugins and replacing the names

**Comment by actionless** [comment]
found and fixed one more small problem: https://github.com/themix-project/oomox/commit/595637a429bfa8e2b2e988ec1fb39bfe50a9451a

**Comment by gusbemacbe** [comment]
I was not aware of it. I am sorry. I will be more attentive in the next commit.

**Comment by actionless** [comment]
no, it was introduced by me previously when adding gradients

just let you know about it :-)

**Comment by actionless** [comment]
btw please check with the latest git version if theme options are displayed as expected when you switch gradient on/off or changing them and so on or something still need to be improved

**Comment by gusbemacbe** [comment]
Hello @actionless 

* Suru++:

![Oomox - Suru++](https://user-images.githubusercontent.com/2257024/54096651-71300b80-438b-11e9-88ad-b6a4d096c906.gif)

* Suru++ Asprómauros:

![Oomox - Suru++ Asprómauros](https://user-images.githubusercontent.com/2257024/54096662-7db46400-438b-11e9-98bd-0e75844bffeb.gif)

**Comment by actionless** [comment]
i was asking you just to confirm like "yes"/"no" :-)

but thanks for your screencasts, mb it could be worth adding them somewhere to readme of oomox or suru icons

**Comment by gusbemacbe** [comment]
> but thanks for your screencasts, mb it could be worth adding them somewhere to readme of oomox or suru icons

They are ideal for Oomox noobies. They asked me where the exported icons theme are.

**Comment by actionless** [comment]
so at the moment i've created a wiki article: https://github.com/themix-project/oomox/wiki/Customizing-icon-themes

mb with the time more info could be appended to it

**Comment by gusbemacbe** [comment]
I can do it for you if you want.

**Comment by actionless** [comment]
idk, as for me it's too obvious to require nay documentation but if you're saying what users are asking about it -- mb it makes sense

**Comment by gusbemacbe** [comment]
@actionless 

I updated the documentation Customizing icons theme, I hope it be worthy for you.

**Comment by actionless** [comment]
thanks a lot! looks detailed!
