### ISSUE TITLE
Deb files refusing to install.

### ISSUE THREAD

**Issue by ben2talk** [themix-project/oomox#235]
After downloading these .deb files, gdebi-gtk simply freezes and needs force quit.

**Comment by actionless** [comment]
have you tried following instructions from readme?
https://github.com/themix-project/oomox#debian-ubuntu-linux-mint

**Comment by ben2talk** [comment]
> have you tried following instructions from readme?
> https://github.com/themix-project/oomox#debian-ubuntu-linux-mint

I did and it worked, but that's after I first downloaded and got them to freeze and force quit.

**Comment by actionless** [comment]
there's already open ticket for improving this process: https://github.com/themix-project/oomox/issues/144
