### ISSUE TITLE
Arc submodule points to branch that does not exsist

### ISSUE THREAD

**Issue by Jesse-Millwood** [themix-project/oomox#236]
The arc-theme submodule points to an oomox branch that does not exist for that repository.

**Comment by actionless** [comment]
it looks fine: https://github.com/themix-project/oomox/tree/master/plugins/theme_arc

even in github UI you can click on it and will open you that commit in their repo

**Comment by actionless** [comment]
i did updated the submodule about 12 hours before you created the issue, but even before it seems to be fine: https://github.com/themix-project/oomox/commit/25e2104e6b517a34334bf705e34525153984f818

mb you have some very old local copy (like 2-4 months old or more) which points to some testing branch which was already removed?

**Comment by Jesse-Millwood** [comment]
Ah I see that now. But in the `.gitmodules` it shows 
I was checking out version 1.11. I'll patch my ebuild to grab the commit version then. Since the branch doesn't seem to exist in that repo anymore.

**Comment by actionless** [comment]
Mb use 1.12 for your ebuild

**Comment by Jesse-Millwood** [comment]
ah I see that was just tagged. Will update!

**Comment by actionless** [comment]
there will be new submodules in 1.12

and in upcoming 1.12.1 (1.13?) too
