### ISSUE TITLE
Oomox does not compile themes

### ISSUE THREAD

**Issue by FhilipeCrash** [themix-project/oomox#243]
when trying to compile the theme it shows the error lines

cp: could not get 'gtk-darker.css' status: nonexistent file or directory
make [3]: *** [Makefile: 562: darker / gtk-main.css] Error 1
make [3]: ** Waiting for other processes to finish.
cp: could not get 'gtk-dark.css' status: nonexistent file or directory
Make [3]: *** [Makefile: 564: darker / gtk-main-dark.css] Error 1
rm darker / assets
make [3]: Leaving directory '/tmp/tmp.TUDS2kHFlQ/common/gtk-3.0/3.20'
make [2]: *** [Makefile: 428: install-recursive] Error 1
make [2]: Leaving directory '/tmp/tmp.TUDS2kHFlQ/common/gtk-3.0'
make [1]: *** [Makefile: 435: install-recursive] Error 1
make [1]: Leaving directory '/tmp/tmp.TUDS2kHFlQ/common'
make: *** [Makefile: 360: install-recursive] Error 1

I do not know why this happens.

**Comment by actionless** [comment]
please install it following the readme file: https://github.com/themix-project/oomox/blob/master/README.md
