### ISSUE TITLE
what is the origin of pixmap "detail"

### ISSUE THREAD

**Issue by vunugox** [themix-project/oomox#244]
This is not an issue related to oomox.

There are plenty of stuff like this:

```
engine "pixmap" {
  image {
    function = ...
    detail = ???
    ...
    file = ....
    ...
   }
}
```
and a very limited amount of documentation to my knowledge. What I have found is that "detail" can be `<any string>`.

For example I found in oomox generated theme
`detail = menu_scroll_arrow_up`
but nothing similar in pixmap module sources.

Where this "any string" of `detail` comes from?

**Comment by actionless** [comment]
https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkEngines/PixmapEngine

**Comment by actionless** [comment]
your personal google assistant always at your service

**Comment by vunugox** [comment]
where do you get your strings? there are some defined in gtkstyle.c but others are not, are they deprecated / imaginary?

**Comment by actionless** [comment]
is there a reason why you decided ask it here instead of gnome community?

**Comment by vunugox** [comment]
yes, gnome community hates me
