### ISSUE TITLE
Meteria accent on gtk-dark.css 

### ISSUE THREAD

**Issue by lelgenio** [themix-project/oomox#251]
Editing the accent color does not seam affect gtk-dark.css
steps to reproduce:
- make a theme with different accent color
- open a gtk program which uses gtk-dark.css(totem, eog)
most notably the progress-bar on totem is always blue

also, this can be fixed by generating materia dark with the same accent color and replacing gtk-dark.css:
```bash
mv oomox-materia-dark/gtk-3.0/gtk.css oomox-materia/gtk-3.0/gtk-dark.css
```

**Comment by actionless** [comment]
create it in materia repo
