### ISSUE TITLE
feature request: gtk3 color scheme for terminal and co like Xresources

### ISSUE THREAD

**Issue by GitHubRepositoryX** [themix-project/oomox#255]
Hey Guys,

It would be nice if oomox could also export color schemes for gtk3, so gtk apps output matches alacritty or urxvt (Xresources).

Thanks for the oomox development, I like it a lot :)

**Comment by actionless** [comment]
read this guide please: https://github.com/themix-project/oomox/wiki/How-to-import-and-export-Base16-themes-in-Themix-Oomox

**Comment by GitHubRepositoryX** [comment]
> read this guide please: https://github.com/themix-project/oomox/wiki/How-to-import-and-export-Base16-themes-in-Themix-Oomox

I don't mean that, alacrritty is not an gtk app. I mean native gtk apps like gnome-terminal, running on wayland. Xresources dont work on wayland. And I have already an alacritty.yml.

**Comment by actionless** [comment]
which particularly gtk apps do you mean?

**Comment by GitHubRepositoryX** [comment]
> which particularly gtk apps do you mean?

I mean every output generated by gtk-apps in general. gnome-terminal for example hast the option the change the color palette in the settings menu. or syntax highligthing in gedit, which use the default color palette.

![captue](https://user-images.githubusercontent.com/53064520/62148757-9d2c3900-b2fa-11e9-9261-348c7403e69a.png)

**Comment by actionless** [comment]
gnome-terminal is also supported by base16 export plugin

>> /themelocation/oomox-themename/gtk-3.20/gtk.css

look in /themelocation/oomox-themename/gtk-3.20/dist/gtk.css

if you have some suggestions for the generated theme feel free submitting a PR

**Comment by actionless** [comment]
also AFAIR gedit using gtksourceview's xml themes, mb try to find a base16 template for it, and if you'll succeed or will write one -- you could add it here: https://github.com/chriskempson/base16-templates-source
