### ISSUE TITLE
wiki : Customizing icon themes

### ISSUE THREAD

**Issue by yuceltoluyag** [themix-project/oomox#257]
https://github.com/themix-project/oomox/wiki/Customizing-icon-themes#where-is-the-icons-theme-customization Pictures 404 not found lul

**Comment by actionless** [comment]
cc @gusbemacbe

**Comment by gusbemacbe** [comment]
Today or tomorrow I will fix it.

**Comment by gusbemacbe** [comment]
I cloned the wiki project, but I can not push to the wiki, @actionless, because I am not collaborator. I am only a contributor.

I have to send the packed file to you that you will clone your wiki page and replace with the packed file, and push.

**Comment by actionless** [comment]
i've tried to set the permission, but on github i could do push permission only for the whole repository (not only for the wiki)

so you could just fork the repo, and next i'll merge it manually from there

**Comment by gusbemacbe** [comment]
I git-pull-upstreamed your repository, but the wiki is not included, so I have to accept your invite for pushing the wiki pages.

**Comment by gusbemacbe** [comment]
1. Clone your own wiki pages on the terminal: `git clone https://github.com/themix-project/oomox.wiki.git 'oomox-wiki`;
2. Go to the folder `oomox-wiki` and delete everything;
3. Download and extract:
[oomox-wiki-yak.zip](https://github.com/themix-project/oomox/files/3499087/oomox-wiki-yak.zip)
4. Copy and paste everything to the folder `oomox-wiki`;
5. Run the commands `git add .`, `git commit` and `git push`, with your username and password.
6. Ready. See how new wiki pages is like. I hope you like.

**Comment by gusbemacbe** [comment]
@actionless

**Comment by actionless** [comment]
@gusbemacbe 

sorry for the delay, wasn't on github for the last few days

really great work on translating and restucturing it

thanks a lot!

**Comment by actionless** [comment]
@gusbemacbe i've just double-checked the image links are still not working:

https://github.com/themix-project/oomox/wiki/Customizing-icon-themes
https://github.com/themix-project/oomox/wiki/Pictogrammenthema-aanpassen

**Comment by gusbemacbe** [comment]
Hello @actionless !

I tested and it worked. Ready. Download the compressed file [oomox-wiki-gus.tar.gz](https://raw.githubusercontent.com/wiki/gusbemacbe/oomox/oomox-wiki-gus.tar.gz). Copyt everything and overwrite everything.

**Comment by actionless** [comment]
sorry for the delay, had some personal things to solve

thanks a lot, i've tested few pages -- looks good now!
