### ISSUE TITLE
Dark-style Arc themes have ugly black borders and divisors.

### ISSUE THREAD

**Issue by MrSenshi** [themix-project/oomox#260]
![ArcThemeFault](https://user-images.githubusercontent.com/49480075/64486539-4a616d80-d226-11e9-86ab-94db87bef0f1.png)

If you look at the window border and the border of the popups as well as the divisors under an Arc-based dark theme made with Oomox, you'll notice the color is black. It would most definitely be more suitable if this color was brighter than the background color, rather than being darker.

**Comment by actionless** [comment]
if the issue is reproducible when running https://github.com/NicoHood/arc-theme/blob/2c45d9e4b4a120201dc029a10937058a2e9e094b/change_color.sh manually then create your issue there
