### ISSUE TITLE
E: The package oomox needs to be reinstalled, but I can't find an archive for it.

### ISSUE THREAD

**Issue by KShivendu** [themix-project/oomox#267]
I downloaded the software from the releases for my Ubuntu 19. Tried installing it with dpkg -i oomox_1.12.4-1-g3d3b5584_17.04+.deb. 
Now i can't install anything on my laptop .

sudo apt install <something> shows:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: The package oomox needs to be reinstalled, but I can't find an archive for it.

I have tried: 
1. sudo apt-get remove --purge oomox && sudo apt-get update && reboot
2. sudo dpkg --remove --force-all oomox && sudo apt-get update && reboot
3. sudo rm /var/lib/apt/lists/* -vf && sudo apt-get update && reboot.

Please help me out.

Thanks

**Comment by KShivendu** [comment]
Also while trying to re-install with dpkg it doesn't go beyond this :

Selecting previously unselected package oomox.
(Reading database ... 498329 files and directories currently installed.)
Preparing to unpack oomox_1.12.4-1-g3d3b5584_17.04+.deb ...
Unpacking oomox (1.12.4-1~themixproject~zesty) over (1.12.4-1~themixproject~zesty) ...

**Comment by KShivendu** [comment]
sudo dpkg --remove --force-all oomox has output : 
                  
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: package is in a very bad inconsistent state; you should
 reinstall it before attempting a removal
(Reading database ... 498328 files and directories currently installed.)
Removing oomox (1.12.4-1~themixproject~zesty) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.32.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-4ubuntu1) ...
Processing triggers for mime-support (3.60ubuntu1) ...

**Comment by KShivendu** [comment]
sudo mv /var/lib/dpkg/info/oomox.* /tmp/                         
sudo dpkg --remove --force-remove-reinstreq oomox
sudo apt-get remove oomox
sudo apt-get autoremove && sudo apt-get autoclean

Solved it.
Now I can install other things
But can anyone please tell me how to install it for Ubuntu 19

Thanks

**Comment by actionless** [comment]
please read the readme more carefully:

> ./oomox_VERSION_18.10+.deb for Ubuntu 18.10+

**Comment by actionless** [comment]
if you want to have a more automated installation process on ubuntu feel free to collaborate on this: https://github.com/themix-project/oomox/issues/144
