### ISSUE TITLE
Export icons fails with Debian package

### ISSUE THREAD

**Issue by alexarnaud** [themix-project/oomox#268]
Hello,

Environment:
- Debian 10 "Buster"
- Oomox 12.4-2-g99e64ec5_18.10+.deb

Steps to reproduce:
1) Open Oomox
2) Choose Modern Arc Dark then Materia
3) Click on "Export icons" (translated from French)

The export fail with the following output:
> /opt/oomox/plugins/icons_gnomecolors/gnome-colors-icon-theme/change_color.sh: ligne 116: make : commande introuvable

I obtain a similar result with "Export themes".

Best regards.

**Comment by actionless** [comment]
how is called the package name which holds `make` executable on that debian?
it seems that package is missing in oomox deb package manifest

**Comment by alexarnaud** [comment]
I'm not sure to understand what you're requesting.

I'm running oomox from the desktop file on Mate preferences.

The exec line is:
> Exec=oomox-gui

Best regards.

**Comment by actionless** [comment]
`apt-file search make`

**Comment by actionless** [comment]
added 2f9b3bbd4fba44ff277ed88ab39cde4765129b06

please try the updated package: https://github.com/themix-project/oomox/releases/tag/1.12.4

**Comment by alexarnaud** [comment]
I've in first place tested the package "oomox_1.12.4-9-g54085fca_17.04+.deb" and it doesn't seem to have the needed dependencies.

Then I've tested "oomox_1.12.4-11-g7bcc540d_18.10+.deb" ans I confirm it has the correct dependencies.

Many thanks for fixing this.

Best regards.

**Comment by actionless** [comment]
thanks for investigating and reporting this as well!
