### ISSUE TITLE
Where to see which colors i need to change?

### ISSUE THREAD

**Issue by joe23reptiles** [themix-project/oomox#269]
hi- the program itself is fine. no isses here. but i have an issue with the colors. ive created my theme (numix based). everything is fine. exept for the look of the pamac manager. ive a dark blue theme with light green and royal blue highlights. but when im opening it, the buttons for "install" or "remove" have an orange background with green font. looks horrible. within oomox theres no option which ive selected to turn it orange. 

what i tried so far:

tried to change /gtk-3.20/dist/gtk.css and /gtk-3.0/dist/gtk.css

selected all orange colors i could find and changed them (took a couple of hours even tho i used find and replaced quite a bit, because there wasnt a certain orange color but 8 or 9 differrent). 

how to recreate it- install the newest version of pamac manager in arch and set up a dark numix based theme within oomox. then set it as theme for gtk apps.

sooo- is there anything else i could try? 

is there maybe a little tool i could use which tells me where the code for the button i want to change is located at?

or is there a basic config i could change which set the default colors for these buttons?

**Comment by actionless** [comment]
try using gtk inspector on pamac to figure out which style is causing it

**Comment by joe23reptiles** [comment]
thanks. if someone else has the same problem- the colors get pulled from the terminal colors. so one has to change the terminal colors to fit the rest of the theme.
