### ISSUE TITLE
Compiling Debian package following the README failed

### ISSUE THREAD

**Issue by alexarnaud** [themix-project/oomox#271]
Hello,

Following the instruction on the README I'm running:

> ./packaging/ubuntu/create_ubuntu_package.sh control_1810

It compiles correctly and installs correctly but at run time I obtain the following issue:
> error loading oomoxify plugin (translated from French)
(Indeed in the oomoxify plugin is an empty directory at /opt/oomox/plugins/oomoxify/)

Do I misreading the procedure or we should add something in the compilation process?

Best regards.

**Comment by actionless** [comment]
how did you cloned the repo? https://github.com/themix-project/oomox#installation-1

**Comment by alexarnaud** [comment]
@achadwick Yes you're right. It was the issue, I've forgotten the --recursive option.

Probably indicating that in the compilation of the Debian packages could help.

Other stuff not related is the debian package should have the "_all" suffix are require by the Debian policy and also to help users being aware that the package is not architecture dependent.

Best regards.

**Comment by actionless** [comment]
could you please make a PR for _all? (in this file: https://github.com/themix-project/oomox/blob/master/maintenance_scripts/tag_release.sh#L42-L43)
i'm not sure in which position of the version that string should be

also feel free to update the documentation if needed

**Comment by alexarnaud** [comment]
Le 23/10/2019 à 15:07, Yauhen Kirylau a écrit :
> could you please make a PR for _all? (in this file: 
> https://github.com/themix-project/oomox/blob/master/maintenance_scripts/tag_release.sh#L42-L43 
> <https://github.com/themix-project/oomox/blob/master/maintenance_scripts/tag_release.sh#L42-L43>)

I'm not sure to understand. The version field of the package is OK but 
the package faile name should be *_all.deb.

As I've seen the package is named oomox.deb and I don't see any 
reference to the oomox.deb file in the script you've mentioned.

Best regards.

**Comment by actionless** [comment]
i see, in that case see here:

https://github.com/themix-project/oomox/blob/master/packaging/ubuntu/docker_ubuntu_package.sh#L47
