### ISSUE TITLE
Compiling the Debian package in non-root user no longer work

### ISSUE THREAD

**Issue by alexarnaud** [themix-project/oomox#272]
Hello,

When compiling the Debian package today I've encounter an issue due to the recent changes to test the installation of the package.
See the logs obtain with running the package construction with "bash -x":

> dpkg-deb: building package 'oomox' in 'oomox.deb'.

> + apt install -y --no-install-recommends ./oomox.deb
> E: Impossible d'ouvrir le fichier verrou /var/lib/dpkg/lock-frontend - open (13: Permission non accordée)
> E: Impossible d'obtenir le verrou de dpkg (/var/lib/dpkg/lock-frontend). Avez-vous les droits du superutilisateur ?

Best regards.

**Comment by actionless** [comment]
i think it still works -- please check for oomox.deb file generated in the working directory
