### ISSUE TITLE
Oomox on Ubuntu 19.10 fails to install

### ISSUE THREAD

**Issue by gsbhasin123** [themix-project/oomox#277]
I just updated to Ubuntu 19.10 from 18.04, first updating from 18.04>19.04 and then 19.04>19.10. I noticed that oomox was uninstalled, so I reinstalled. I used the 18.10+ DEB, but it doesn't install, claiming that it doesn't have access to a certain filepath: 
```
(Reading database ... 524639 files and directories currently installed.)
Preparing to unpack oomox_1.12.4-11-g7bcc540d_18.10+.deb ...
Unpacking oomox (1.12.4-1~themixproject~cosmic) ...
dpkg: error processing archive oomox_1.12.4-11-g7bcc540d_18.10+.deb (--install):
 unable to open '/opt/oomox/plugins/icons_numix/numix-icon-theme/Numix/16/actions/align-horizontal-bottom-out.svg.dpkg-new': Operation not permitted
Processing triggers for desktop-file-utils (0.24-1ubuntu1) ...
Processing triggers for mime-support (3.63ubuntu1) ...
Processing triggers for gnome-menus (3.32.0-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 oomox_1.12.4-11-g7bcc540d_18.10+.deb
```
(and yes, I'm running `dpkg -i` with `sudo` ofc... the command used was `sudo dpkg -i oomox_1.12.4-11-g7bcc540d_18.10+.deb`.) 

I tried deleting the whole /opt/oomox with `sudo rm -rf /opt/oomox`; no effect, same deb output.
PLEASE HELP; This is vital for my theme, https://gitlab.com/Gsbhasin84/materiav2

**Comment by actionless** [comment]
as i see from the output it's some problem either with dpkg database or filesystem health

please try to consult the support resources of your distribution

**Comment by gsbhasin123** [comment]
I fixed it by temporarily installing the flatpak but ok, did you test on 19.10 tho @actionless? Just curious

**Comment by actionless** [comment]
it's not the first time i receive an issue with a similar log (not depending on distribution), most of the time it was being fixed by `fsck` or so

**Comment by gsbhasin123** [comment]
Alright, thanks. What's `fsck`, and is it safe to run?

**Comment by gsbhasin123** [comment]
Also the flatpak fails:
```
Error: While pulling app/com.github.themix_project.Oomox/x86_64/stable from remote flathub: Server returned status 503: Service Unavailable
error: Failed to install com.github.themix_project.Oomox: While pulling app/com.github.themix_project.Oomox/x86_64/stable from remote flathub: Server returned status 503: Service Unavailable
```

**Comment by gsbhasin123** [comment]
Not an Oomox issue @actionless ;) It was a sophos antivirus issue: https://discourse.ubuntubudgie.org/t/corrupted-filesystem/2731/9

**Comment by actionless** [comment]
> Not an Oomox issue @actionless ;)

i knew that ;)

thanks for update anyway, glad to know it's working all fine now
