### ISSUE TITLE
Generate a pre-compiled Debian package

### ISSUE THREAD

**Issue by alexarnaud** [themix-project/oomox#278]
Hello,

Currently at each installation Oomox is compiled and that takes many times.

This will be useful for two stuff:
- It'll be faster for people with a relatively good connection.
- It'll allow to easily prevent disk space issues, APT couldn't detect the size of the package before installing it and so a user can completely fill its hard drive.

Best regards.

**Comment by actionless** [comment]
it is already done for few years: https://github.com/themix-project/oomox#debian-ubuntu-linux-mint

**Comment by alexarnaud** [comment]
> it is already done for few years: https://github.com/themix-project/oomox#debian-ubuntu-linux-mint

I was probably not clean but the Debian packages are indeed generated but not pre-compiled. At the end of the postinst process there is this line:
python3 -O -m compileall /opt/oomox/oomox_gui

The package already available takes 50M to download but almost 600mb after installation.

I think we could propose to have a pre-compiled package (before installation).

**Comment by actionless** [comment]
could you show me those 550 MB of *.pyc files?

**Comment by alexarnaud** [comment]
OK, my bad. The huge installation time (10 minutes) is only due to the huge amount of themes / icons. 

The latest version takes 550MB on disk whereas the version 1.2.6 takes 30MB on disk.

Do you know which plugins / icons / themes should I keep to have the same feature as of version 1.2.6?

I'd like to reduce the size and installation time of Oomox because the amount of icons / themes / plugins was sufficient for our downstream need. 

Also "only" having essential theme will be easier for our users (usually not power users).

Sorry for all that question. I'm looking at finding the best compromise between feature and simplicity. 

We customize theme for visual-impaired or elderly people.

Best regards.

**Comment by actionless** [comment]
i recommend you to do smth like `cd /opt/oomox && ncdu .` to see for yourself, but yeah, most of the space are taking the new icon packs

**Comment by actionless** [comment]
also please see/participate in https://github.com/themix-project/oomox/issues/129 regarding splitting the main themix-gui and plugins into separate packages
