### ISSUE TITLE
Arc Dark does not correlate to oomox Arc Dark

### ISSUE THREAD

**Issue by TheBabu** [themix-project/oomox#286]
The Arc Dark theme does precisely match the provided Arc Dark theme by oomox, and I believe this is true for any variant of the Arc themes.

Normal Arc Dark:
![Screenshot_2020-03-11_16-28-12](https://user-images.githubusercontent.com/24832107/76476866-c187e200-63c0-11ea-8e0a-e8a2227b4f04.png)
oomox Arc Dark:
![Screenshot_2020-03-11_16-27-56](https://user-images.githubusercontent.com/24832107/76476874-cb114a00-63c0-11ea-84cd-a6ef7e23971a.png)

There are three differences that you can see in the screenshots. First is the checkbox coloring, second is the background color of the dropdown menu, and third if you look at the list of avaliable themes you can see that color font for a selected item is dark instead of light.

Is there a way to manually fix these issues, so that my custom Arc Theme can work?

**Comment by actionless** [comment]
if you still can reproduce the issue when running directly https://github.com/arc-design/arc-theme/blob/master/change_color.sh then nothing could be fixed on the oomox side

**Comment by TheBabu** [comment]
I'm attempting to transcribe all of the sections in this command: `./change_color.sh --autogen-opts '--disable-gnome-shell' --output Arc-Custom <(echo -e "BG=282828\nTXT_FG=d0d0d0\nHDR_BG=282828\nHDR")`, but it is difficult because you don't use those IDs in the oomox program, could you please specify what element in the GUI corresponds to what ID in the scrip command?

**Comment by actionless** [comment]
instead of "transcribing" theme values you can just specify the path to the theme file (see what `<()` means in `bash`)

**Comment by TheBabu** [comment]
It seems to be reproducible in the above script. Is there a way to use these values in the new upstream arc theme?

**Comment by actionless** [comment]
i dunno, wasn't looking into it
