### ISSUE TITLE
How to implement support for other terminal theme formats? (UI)

### ISSUE THREAD

**Issue by AKAStacks** [themix-project/oomox#289]
On the main GUI's title-bar there is an "Export Terminal" button, which generates Xresources.
I use xfce4-terminal, and want to be able to export in that themed format directly from Oomox.

I plan to start working on this tomorrow evening, but if you see this in the mean time: how would you like something like that implemented on the GUI? Drop-down from "export terminal" title-bar button?

**Comment by actionless** [comment]
add base16 template to https://github.com/chriskempson/base16-templates-source or https://github.com/themix-project/themix-plugin-base16/blob/0ebeec2b96384dcd9f4aea499bb16997f65b95c8/templates_extra.yaml and next export with https://github.com/themix-project/oomox/wiki/How-to-import-and-export-Base16-themes-in-Themix-Oomox

**Comment by AKAStacks** [comment]
Oh, cool--someone has done it already.

**Comment by actionless** [comment]
however good what you raised the point -- it might make sense to remove "Export terminal" button and instead add "Export Xresources" to the menu on the right

**Comment by actionless** [comment]
^ done
