### ISSUE TITLE
Change Materia View Color in CLI?

### ISSUE THREAD

**Issue by jacobhilker1** [themix-project/oomox#290]
Hi there!

I am currently using the excellent [Chameleon](https://github.com/GideonWolfe/Chameleon) for theming my various applications at once, and I was wondering if there was some way I could use the background color from the image as the view color? For instance, since I have 0a0000 as the background color from my image, I'd like to use 0a0000 as my View color as well.

Thanks!

**Comment by actionless** [comment]
in Themix GUI:
1) choose Import -> Colors from Image
2) choose the image
3) the image colors would be assigned to the theme, you can rearrange them manually
4) click "Export Theme..."
