### ISSUE TITLE
Issue With Materia Themes

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [themix-project/oomox#292]
If you create your own variant of Materia (in this case I literally just changed the highlight colour to green) you get this odd looking delete button in Gnome 3.34.
![Screenshot from 2020-03-28 23-18-22](https://user-images.githubusercontent.com/7698035/77836034-7ef93000-714a-11ea-972b-35739fd07753.png)

**Comment by actionless** [comment]
please create the issue in the materia theme repo

**Comment by KUPOinyourWINDOW** [comment]
It's only present on Materia themes generated via Oomox, it's not present upstream in the actual Materia theme.

**Comment by actionless** [comment]
you mean you can't reproduce it when running https://github.com/nana-4/materia-theme/blob/master/change_color.sh manually?
