### ISSUE TITLE
Arc theme export stucks and takes all ram

### ISSUE THREAD

**Issue by zygmund2000** [themix-project/oomox#293]
Hi,

I have a problem with export Arc based themes, it takes all 16GB ram and all 16GB swap and crash my system, Arch linux kernel_5.4.28 x86_64, how to fix that?

______________________________________________

### Workaround №2: https://github.com/themix-project/oomox/issues/293#issuecomment-608347348

**Comment by dontdieych** [comment]
Hello, same problem here.

On 15.5G RAM + 8G SWAP, build failed. Before build failed. whole memory + swap was full. Tried default arc-dark theme.

Thanks.

```
uname -a
Linux a 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux
```

**Comment by actionless** [comment]
that's a bug in Arc theme

(see nana-4/materia-theme#407 and https://gitlab.gnome.org/GNOME/gtk/issues/2237 for more detailed explanation of the issue and how to fix it)

however Arc theme got abandoned again recently: https://github.com/arc-design/arc-theme/commit/53e61887451358a859fd07de12e3d3b58585233e

**Comment by actionless** [comment]
to workaround it you can (downgrade)[https://aur.archlinux.org/packages/downgrade] both `libsass` and `sassc` to `3.6.0` or `3.6.1`

**Comment by actionless** [comment]
also [Flatpak package](https://flathub.org/apps/details/com.github.themix_project.Oomox) have bundled rather old libsass/sassc versions so there it also should work

**Comment by dontdieych** [comment]
I've found 'baloon' and 'Gnome-Colors: shiki-brave also failed very immediately showed couple of lines. Lauhced oomox-gui in terminal but no ouput.

Thanks for reply.

**Comment by actionless** [comment]
@dontdieych those i can't reproduce, please create a separate ticket with more details

**Comment by zygmund2000** [comment]
I confirm with libsass and sassc 3.6.1 it works.

**Comment by actionless** [comment]
In the upcoming Themix distribution releases support for Arc theme will be dropped: https://github.com/jnsh/arc-theme/issues/47 since new upstream developers have no interest in it.

**Comment by actionless** [comment]
For Flatpak release mb it will stay til GTK 4

**Comment by codydafoxie** [comment]
unfortunately with:

sassc -v
sassc: 3.6.1
libsass: 3.6.1
sass2scss: 1.1.1
sass: 3.5

and 

sassc -v
sassc: 3.6.0
libsass: 3.6.0
sass2scss: 1.1.1
sass: 3.5

it doesn't work.
i think i'm lost

**Comment by actionless** [comment]
i think it doesn't work because you're trying to downgrade to 5 years old lib versions

i think you just need to give up unless you're going to resurrect that theme support as a maintainer - because even if you'll get it working, it still would be 5+ years old version of the Arc theme...
