### ISSUE TITLE
Can't install on Fedora 32

### ISSUE THREAD

**Issue by 2l42h3r** [themix-project/oomox#296]
Oomox can't be installed on Fedora 32 from the tcg/themes copr repo due to the fact that Fedora does not package pystache as of 32.

**Comment by actionless** [comment]
cc @LaurentTreguier

**Comment by actionless** [comment]
@2l42h3r  in the meantime you could use flatpak release

**Comment by 2l42h3r** [comment]
> @2l42h3r in the meantime you could use flatpak release

I am, but obviously it's very much inferior to a native build due to sandboxing (no spotify theme, can't import colors from picture, etc.)

**Comment by actionless** [comment]
you also can install it manually (https://github.com/themix-project/oomox#other-distributions) and just skip `base16` plugin which require pystache

or alternatively run oomox inside venv, and install those python deps inside the venv

**Comment by LaurentTreguier** [comment]
I just tried building a `python3-pystache` package for Fedora 32, however it didn't build properly; I suspect this could be some incompatibility with python 3.8. `pystache`'s latest version is from 2014 when I look at its releases on pypi, and that's probably why it has been removed from Fedora packages.
I'm not sure what to do about this.

**Comment by actionless** [comment]
@LaurentTreguier 
try to copy the lines from the PKGBUILD which i currently maintain in AUR:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-pystache

**Comment by LaurentTreguier** [comment]
Thanks @actionless, the test phase trick worked
@2l42h3r There's a `python3-pystache` package in tcg/devel now, so the `oomox` package can be installed

**Comment by 2l42h3r** [comment]
It works, thanks a lot.

**Comment by actionless** [comment]
big thanks for your work on maintaining the repo up-to-date, @LaurentTreguier !
