### ISSUE TITLE
system freezes

### ISSUE THREAD

**Issue by RossComputerGuy** [themix-project/oomox#297]
Every time I try to export a theme, the entire computer freezes up. Is there a solution to this? I'm on Arch Linux with a Ryzen 5 3600, 16GB of RAM, and an RTX 2060.

**Comment by actionless** [comment]
isn't it the same as the pinned issue? https://github.com/themix-project/oomox/issues/293

**Comment by RossComputerGuy** [comment]
Oh, I didn't see that as I was on mobile.
