### ISSUE TITLE
Desktop icon text same as selection foreground on Numix

### ISSUE THREAD

**Issue by s01ch1r0** [themix-project/oomox#298]
I use a black and green theme where the highlight foreground is black, which is also the background color of my desktop. This isn't a problem on Materia (and I can't test on Arc because of the freezing issue). I would use Materia but I can't specify a selection color, only a background color, so anything highlighted becomes solid green. Is there a line of CSS I could add to the gtk3.0 file to overwrite the imported theme and make the icon text another color? Or any way to solve this?

**Comment by actionless** [comment]
i have no idea what css classes your desktop icons might have, try finding it out using `GTK Inspector` or in other way

global override of gtk theme is described here: https://github.com/themix-project/oomox#extra-gtk3-css-hacks
