### ISSUE TITLE
No more text component for Base16 Export Options

### ISSUE THREAD

**Issue by TopSlick** [themix-project/oomox#299]
Base16 Export Options
Since upgrade to version 1.13.3, the text component disappeared from the base16 export options dialog. Changing the application and/or variant has no effect at all. 
Amazing application you wrote !

**Comment by actionless** [comment]
no, it didn't disappeared

i guess the app is just not packaged or installed correctly, contact the maintainer of the package you've got and provide there all the logs

if you installing it manually by yourself -- double check the instructions, they're up-to-date

![2020-05-23--1590228466_1579x920_scrot](https://user-images.githubusercontent.com/1655669/82728116-adc8f800-9cee-11ea-8113-50875e7b3e78.png)

**Comment by TopSlick** [comment]
installed on manjaro, using AUR. No manual intall or mods. 

/opt/oomox/plugins/base16/oomox_plugin.py:273: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.templates_homepages = yaml.load(templates_index_file.read())
/opt/oomox/plugins/base16/oomox_plugin.py:165: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(config_file.read())
Traceback (most recent call last):
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 238, in _on_variant_changed
    self.base16_stuff()
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 170, in base16_stuff
    base16_theme = convert_oomox_to_base16(self.colorscheme)
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 74, in convert_oomox_to_base16
    colorscheme["NAME"]
KeyError: 'NAME'

![Screenshot from 2020-05-23 12-33-55](https://user-images.githubusercontent.com/10288679/82728659-2aa9a100-9cf2-11ea-9822-4c5406b0e136.png)

packages installed from AUR (amongst others):
themix-full-git : 1.13.3-1
themix-gui-git : 1.13.3.r0.g29c38910-1
themix-plugin-base16-git : 1.0.1.r2.gcf325dc-1

Thanks for reaction. Let me know if you need further / specific info.

**Comment by TopSlick** [comment]
Removed all themix packages
Cleared cache and all personal config files ~/.config/oomox/*
reinstalled pystache and yaml
reinstalled themix-full-git and themix-plugin-base16-git from AUR
the text box is back

don't know what went wrong, neither how exactly it is solved, but it is solved. thanks for guiding me in this one, and thanks for this marvelous program. I consider this topic as closed.

**Comment by actionless** [comment]
thanks for finally uploading the log :)

if you check the first error line (` /opt/oomox/plugins/base16/oomox_plugin.py:273`) and compare it to the actual source code (`https://github.com/themix-project/themix-plugin-base16/blob/0e93b2fcfe66e1b37790d4b82541702fc6ac6e55/oomox_plugin.py#L273`) you'll see what the file wasn't updated from 1.13.1 or even 1.12.something

which leads me to the question:

which AUR helper do you use?

can you reproduce the issue using `pikaur`? that would sound funny, but the main reason i wrote it because pacaur/yaourt were stagnating at the moment, and other aur helpers were not always installing/upgrading oomox correctly. and as using arch as a main system such situation was a bit pissing me off personally :D

**Comment by TopSlick** [comment]
both the erroneous install and the correct install (today's one), must have been done with pamac/pacman.  
Neither pacaur, nor pikaur are installed; Got only yay installed but normally don't use it. 
Having a correct install now, can it still be helpful to uninstall themix, install pikaur, and reinstall themix to see whether it's correctly functioning?

**Comment by actionless** [comment]
i just guess what if you continue using the same app for updating aur pkgs -- you'll keep running into the same kind of issues :)

**Comment by actionless** [comment]
if you prefer using GUI tools, i think `octopi` have `pikaur` support

**Comment by TopSlick** [comment]
Right you are, justified remark. I think I'm gonna have a look at pikaur, trying to manage aur from command-line. It'll give me more info, and possibilities in the end. Thanks for the tip.
