### ISSUE TITLE
COPR: CentOS 8: If GTK2 theme still need to be supported, gtk-murrine-engine should be added to the repo

### ISSUE THREAD

**Issue by actionless** [themix-project/oomox#300]
hi, @LaurentTreguier 
it got dropped from el8 EPEL, while was still shipped in el7 [1]

[1]https://dl.fedoraproject.org/pub/epel/7/SRPMS/Packages/g/gtk-murrine-engine-0.98.2-10.el7.src.rpm

if gtk2 theme support is not planned for el8 please let me know to close this ticket

**Comment by LaurentTreguier** [comment]
GTK2 shouldn't still be relevant in 2020... But sadly it is when programs such as Gimp still somehow use it after all these years.
I'll try to see if I can package it for EPEL8
