### ISSUE TITLE
Oomox unable to export theme

### ISSUE THREAD

**Issue by ntzjef** [themix-project/oomox#302]
I have Ubuntu 16.04.6 LTS. These are the last few lines in trying to export my theme:

Makefile:429: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/tmp/tmp.FoQGEEdCSG/common/gtk-3.0'
Makefile:436: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/tmp/tmp.FoQGEEdCSG/common'
Makefile:361: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

I don't know how to fix this.

**Comment by actionless** [comment]
please read this carefully: https://github.com/themix-project/oomox#debian-ubuntu-linux-mint

**Comment by actionless** [comment]
(or use flatpak installation)
