### ISSUE TITLE
Installation requires unavailable configuration

### ISSUE THREAD

**Issue by starhawk64** [themix-project/oomox#303]
I am running Peppermint OS Ten, downloaded literally yesterday.

Relevant terminal output:
```
s********@s******** ~/Downloads $ sudo apt-get install libsass1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libsass1
s********@s******** ~/Downloads $
```

Peppermint OS is based (distantly) on Lubuntu... I found this after two or three other supposedly-simple GTK-theme utilities that likewise didn't work... one that was Python based, in particular, failed rather spectacularly -- I am neither a programmer, nor one who enjoys the company of snakes, and as such, I find its error messages both all too frequent and all too inscrutable.

I just want to be able to make my own simple GTK theme. This shouldn't be this hard.

**Comment by actionless** [comment]
see here: https://github.com/themix-project/oomox#debian-ubuntu-linux-mint
