### ISSUE TITLE
Ooomox not applying spotify theme

### ISSUE THREAD

**Issue by FrenzyExists** [themix-project/oomox#318]
Specs
![image](https://user-images.githubusercontent.com/47986470/85924429-3ee83d00-b860-11ea-89d7-b993323edd68.png)

Problem:
As the title says, Oomox is not applying a custom theme I have for some reason. I'm not sure if it has to do with the fact that I have spicetify. On spicetify I have a gruvbox dark theme, but I want to change that and when I'm doing it on oomox the theme I have with spicetify is still applied

![image](https://user-images.githubusercontent.com/47986470/85924486-adc59600-b860-11ea-9bd5-b9dded85ae7a.png)

Is there any way to override the theme I have with spicetify with oomox or I am just plain dumb and I'm using the wrong tools?

**Comment by actionless** [comment]
contact the spicetify support for this
