### ISSUE TITLE
Oomox won't run on Linux Mint MATE 20?

### ISSUE THREAD

**Issue by dagleykd** [themix-project/oomox#321]
Just installed Oomox over again on my fresh install of Mint MATE 20....installed it through the Software Manager. When I run it, nothing happens, but when I run it from Terminal, I have an error:

`error: runtime/org.gnome.Sdk/x86_64/3.34 not installed`

How would I go about solving this? :)

**Comment by actionless** [comment]
you mean flatpak release?

**Comment by dagleykd** [comment]
I think so? I installed it through the Mint Software Manager

**Comment by dagleykd** [comment]
Just checked....through the Mint Software Manager, but it's listed as using Flatpak, yes.

**Comment by actionless** [comment]
i'll update the gnome runtime in flatpak release during the next hour, thanks for reporting!

**Comment by dagleykd** [comment]
You're welcome! Mint 20 is pretty fresh, so I imagine it has something to do with that! I'll try updating or reinstalling Oomox in the morning and see if your fix helped! 👍 

Cheers and have a good evening! :)

**Comment by actionless** [comment]
done:

https://github.com/flathub/com.github.themix_project.Oomox/commit/ea1f8f7034962e4048a088c3872566acdfe3ebe8
https://flathub.org/builds/#/builders/32/builds/23652

**Comment by dagleykd** [comment]
Perfect, just removed and then reinstalled Oomox and it works fine now...cheers! :)

**Comment by actionless** [comment]
thanks for testing!
