### ISSUE TITLE
Buttons and scrollbar appear too big.

### ISSUE THREAD

**Issue by Swexti** [themix-project/oomox#322]
Heya! So oomox works flawlessly while using it, however when trying to use the theme my buttons are to big.
What it looks like:
![What it looks like](https://user-images.githubusercontent.com/68186933/88456348-4a3d8100-ce7d-11ea-9d0c-b4895208f194.png)
What i want it to look like:
![What i want it to look like](https://user-images.githubusercontent.com/68186933/88456349-4ad61780-ce7d-11ea-9f6d-61dff9fd5ae8.png)
I've tried editing the gtk.css in the /.themes/mytheme/gtk-3.0 at line 518 but it didn't work.
How do i fix this?

**Comment by actionless** [comment]
you've chosen HiDPI scaling for GTK2
