### ISSUE TITLE
Export icons in big sizes, eg 64 x 64?

### ISSUE THREAD

**Issue by cgcgcgcgcg** [themix-project/oomox#336]
Is it possible by editing current TheMix version?
Maybe a future feature with a selection menu?

My issue is I use Tint2 with 55 x 55 sized icons, and have to use the default icons instead of my own, because the ones I generate with TheMix don't have large sizes like 64 x 64 and look pixelated in sizes above 30.

See pic, the 1st blue Kodi icon is from my Dark Ones k17 color theme -thanks for letting us upload those-, the rest from hicolor.
![ksnip_20200925-020751](https://user-images.githubusercontent.com/38960370/94209031-f8909180-fed3-11ea-9aea-6bebfa322f3c.png)

**Comment by cgcgcgcgcg** [comment]
This is using all icons from Dark Ones k17 theme (some are custom).
![ksnip_20200925-021523](https://user-images.githubusercontent.com/38960370/94209468-18748500-fed5-11ea-94be-15aec883403e.png)

**Comment by actionless** [comment]
the repository of those icons is here: https://github.com/gusbemacbe/suru-plus-aspromauros

but AFAIR they are SVG, not PNG

**Comment by cgcgcgcgcg** [comment]
@actionless Yeah, but if you check the installed or github folders you'll see that on 48 and scalable folders there are only symbolic links to 16:
https://github.com/gusbemacbe/suru-plus-aspromauros/blob/master/Suru%2B%2B-Aspr%C3%B3mauros/apps/scalable

**Comment by actionless** [comment]
and in 16 there are SVG files, anyway here is not the place to discuss it
