### ISSUE TITLE
Sidebar gets smaller with export.

### ISSUE THREAD

**Issue by Ritec73** [themix-project/oomox#342]
I've tried a couple stuff and I've looked around. But I can't seem to figure out how to edit the sidebar font size.

Whenever I export a theme on Linux Mint Cinammon. The sidebar gets a lot smaller (see image below, default Mint theme to the left, exported Oomox theme to the right), to the point where it's really annoying. 

![image](https://user-images.githubusercontent.com/74073083/98407539-e6804200-2080-11eb-9f7d-1ad6c602a14a.png)

Does anyone know how I can possibly fix this?

**Comment by actionless** [comment]
i have no idea what are you talking about, mb you'll write it in your native language and i'll try to translate it myself?

**Comment by actionless** [comment]
however this repo is for the GUI app itself

for bugs in the themes, please report the issue to the repository of the theme, which causing this issue
