### ISSUE TITLE
Can't Customize Suru++ Folder icons 

### ISSUE THREAD

**Issue by kushraj** [themix-project/oomox#343]
Using Latest themix-full-git from AUR
This issue is specific to Suru++ Folder icons, ( panel and actions icons have no problem )

Regardless of whatever color I choose for Light/Medium Base and Stroke using oomox-gui, Exported theme is always defaulted to Blue color folder icons as shown in image
![image](https://user-images.githubusercontent.com/36916613/98454656-23395f80-218d-11eb-9b90-3ceee36d9a8a.png)

Is this expected behaviour ?

**Comment by actionless** [comment]
if the issue specific to some of the themes, please create it in according repository: https://github.com/gusbemacbe/suru-plus
