### ISSUE TITLE
Icon preview not displayed on the rightmost panel

### ISSUE THREAD

**Issue by Diaoul** [themix-project/oomox#349]
The preview part of the iconset doesn't show on the right. I have the latest themix-full-git installed on Arch from AUR.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/319220/104087504-79478380-5260-11eb-9443-60308c6b6d33.png)

Console logs:
```
[...]
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
[...]
```

**Comment by Diaoul** [comment]
Fixed by installing python-cairo

**Comment by actionless** [comment]
are you sure you need exactly `python-cairo`, not just `cairo`?

**Comment by Diaoul** [comment]
Yes, I just tried to remove it and the error comes back:
![image](https://user-images.githubusercontent.com/319220/104092012-7610bf80-5281-11eb-8090-f1a9c4519732.png)
![image](https://user-images.githubusercontent.com/319220/104092043-a8222180-5281-11eb-8da6-e3eb9bdda2f3.png)

**Comment by actionless** [comment]
thanks for investigating and double-checking! gonna merge when i will be home (need also to update the packaging for the other destinations)
