### ISSUE TITLE
Spotify: "sed: can't read ./css/*.css: No such file or directory"

### ISSUE THREAD

**Issue by StewartThomson** [themix-project/oomox#351]
Ubuntu 18.04.5
Oomox 1.13.3

When trying to export a theme to spotify (installed via apt spotify-client/stable,now 1:1.1.42.622.gbd112320-37)

The following error occurs:

![image](https://user-images.githubusercontent.com/17557453/104115901-3928e500-52e2-11eb-84bc-6fa81057b8cb.png)

Any suggestions?

**Comment by actionless** [comment]
that's already fixed in current git master: https://github.com/themix-project/oomoxify/commit/b9ab57b647d0748ae15922328978d26ed0353bab
