### ISSUE TITLE
oomox theme issue

### ISSUE THREAD

**Issue by MissLav** [themix-project/oomox#369]
having issues with my custom theme on a gtk IRC client 

here the client is with adwatia dark 
https://user-images.githubusercontent.com/51702517/110846731-bdabcb80-8271-11eb-874c-dfd421a16617.png

and here it is with my custom theme
https://user-images.githubusercontent.com/51702517/110846988-fc418600-8271-11eb-85cb-850c6d1529cc.png

this doesn't really happen with any other program I use

example of a few programs 
https://user-images.githubusercontent.com/51702517/110847341-6d813900-8272-11eb-9a8b-09c591d18529.png

**Comment by MissLav** [comment]
made an issue with the gtk irc client as well
https://github.com/SrainApp/srain/issues/291

**Comment by actionless** [comment]
as i see it broken for other themes as well

but thanks for reporting anyway
