### ISSUE TITLE
Exporting doesn't work

### ISSUE THREAD

**Issue by kevadesu** [themix-project/oomox#375]
I want to export a Materia theme and oomox doesn't show any errors. However, it doesn't show up at the directory no matter what directory, the theme doesn't show up. Running Ubuntu 20.04 LTS Dualboot on a MacBook Pro 2013 Late with macOS Big Sur as it's other OS.

**Comment by actionless** [comment]
have no idea, your report doesnt make it clear

however ubuntu releases are abandoned for long ago (also see https://github.com/themix-project/oomox/issues/144)

so just try building themix-gui and material plugin manually, exactly following instructions in readme for manual installation
