### ISSUE TITLE
Progress bar troughs same color as progress bar

### ISSUE THREAD

**Issue by AVLinux** [themix-project/oomox#377]
Hi,

First thanks for this very useful tool! I'm using version 1.12.5.3 of Oomox.

I have created a set of themes with my own color choices (based on the old 'Diehard4' GTK2 theme) and the Materia and Oomox themes work exactly as expected but the Arc variant has a bug where the troughs are rendered the same color as the progress bars so the progress bars are invisible..? What is extra weird is that Arc themes I create with other colors all work as expected..?

These themes are used in my Distribution (AV Linux) and I would really prefer the Arc theme to be the default because it uses less screen real estate than either Materia or Oomox. I have attached my colors file, please let me know if I can provide any more useful info.

*EDIT the same issue happens with latest 1.13.3 Release as well

[AVL-MXE-Diehard-Arc-Dark-Test.zip](https://github.com/themix-project/oomox/files/6346986/AVL-MXE-Diehard-Arc-Dark-Test.zip)

**Comment by actionless** [comment]
Arc support was dropped, read more here: https://github.com/themix-project/oomox/issues/293
