### ISSUE TITLE
Materia theme creation fails with "mkdir: folder "" can't be created"

### ISSUE THREAD

**Issue by paulhersch** [themix-project/oomox#379]
As the title says, I have an error message saying `mkdir: das Verzeichnis „“ kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden` which roughly translates to "the folder "" can't be  created, file or folder not found"

This only happens with the Materia theme selected, I can dump the full output if needed.

I am using the current git Version from the AUR

**Comment by actionless** [comment]
specify exact version, not name of the package

**Comment by actionless** [comment]
and of materia plugin?

**Comment by paulhersch** [comment]
~ > yay -Q themix-theme-materia-git                                                                                                       
themix-theme-materia-git 20210322.r48.g34bffc10-1

**Comment by actionless** [comment]
then try the following:

```
cd /opt/oomox/plugins/theme_materia/materia-theme
./change_color.sh /opt/oomox/colors/Monovedek/monoteria
```

**Comment by actionless** [comment]
also, whats the "export path" in UI dialog?

**Comment by paulhersch** [comment]
> then try the following:
> 
> ```
> cd /opt/oomox/plugins/theme_materia/materia-theme
> ./change_color.sh /opt/oomox/colors/Monovedek/monoteria  # or better use your theme here, to make sure problem not caused by the theme

`
Running custom install script '/usr/bin/sh -c cp "/tmp/tmp.aurEZFt3CW/_build/src/gtk-3.0/Materia.gtk3.gtk-dark.css" "$MESON_INSTALL_DESTDIR_PREFIX/share/themes/Materia/gtk-3.0/gtk-dark.css"'
Running custom install script '/usr/bin/sh -c cp "/tmp/tmp.aurEZFt3CW/_build/src/gtk-4.0/Materia.gtk4.gtk.css" "$MESON_INSTALL_DESTDIR_PREFIX/share/themes/Materia/gtk-4.0/gtk.css"'
Running custom install script '/usr/bin/sh -c cp "/tmp/tmp.aurEZFt3CW/_build/src/gtk-4.0/Materia.gtk4.gtk-dark.css" "$MESON_INSTALL_DESTDIR_PREFIX/share/themes/Materia/gtk-4.0/gtk-dark.css"'
mkdir: das Verzeichnis „“ kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden

`


> also, whats the "export path" in UI dialog when you do it in the app?

`/home/paul/.themes/oomox-autumn`

this one seems to be correct and working as the Oomox theme exported flawlessly

**Comment by actionless** [comment]
i can't really reproduce the same issue, however i see what my latest 2-3 commits to materia-theme could cause smth similar, i'll look into it

**Comment by paulhersch** [comment]
Thank you very much!

**Comment by paulhersch** [comment]
can i update to the fixed version by rebuilding the AUR package now?

**Comment by actionless** [comment]
the one with materia plugin

**Comment by actionless** [comment]
@paulhersch i suppose the fix helped?

**Comment by paulhersch** [comment]
yes it did, thanks again
didn't say anything because i supposed it would be annoying, sorry if you expected a reply
