### ISSUE TITLE
Problems with GIMP in Materia based theme

### ISSUE THREAD

**Issue by giuli635** [themix-project/oomox#381]
Gimp has a strange problem, I cannot explain it in words, so I'm leaving a picture.

![imagen](https://user-images.githubusercontent.com/75577897/119892325-67fdcb80-bf10-11eb-9644-5d90aa5f70f2.png)

Is a very specific issue, but I don´t know where to ask about it, so I suppose you can give me a hand. Let me know if you need details.

**Comment by actionless** [comment]
please create it in materia repo, this is repo of the GUI app
