### ISSUE TITLE
Template Colors Numix

### ISSUE THREAD

**Issue by geekthought** [themix-project/oomox#384]
Hi, 

i created a template with basically three colors. Everything is fine and dandy. Except that some UI elements have a green color (#CEEB93). For example the equal sign of the calculator on hover (Ubuntu 20.04). Where does this come from and where can i change that. 

![image](https://user-images.githubusercontent.com/41953438/121398347-8b376a80-c955-11eb-8d25-832eb6536ba6.png)

**Comment by actionless** [comment]
Green terminal color
