### ISSUE TITLE
arc theme is maintained at diffeirent repository

### ISSUE THREAD

**Issue by pva** [themix-project/oomox#385]
I've noticed that arc dark them uses the following URI: https://github.com/NicoHood/arc-theme.git Yet that repository has the following message at the beginning of README:

This project needs new maintainers to continue. The current maintainers do not have the bandwidth to continue. As such this project has now been put into archive readonly mode. The theme is actively maintained under a separate project at github.com/jnsh/arc-theme.

It's necessary to update URI in oomox as well. TIA

**Comment by actionless** [comment]
the ticket is even pinned to the top :facepalm:  : https://github.com/themix-project/oomox/issues/293
