### ISSUE TITLE
Export to materia does not work

### ISSUE THREAD

**Issue by Kommynct** [themix-project/oomox#387]
I can't seem to force the program to use resvg, I even tried uninstalling inkscape

When using inkscape it takes FOREVER to export the theme and inevitably fails. Is there some way to force resvg that i'm missing?

inkscape gives a ton of 

"More than 32 iteration while updating document" errors while going, if you need logs/something to test with please let me know, I can't seem to extract the logs from the program and am not familiar with how it works.

Compiled on arch with themix-full-git, themix-gui-git and themix-materia-git all compiled today.

**Comment by actionless** [comment]
do you mean it happens only when you use themix-gui and not happens when you manually run ./change-color.sh script from bare materia repo?

**Comment by Stardust-kyun** [comment]
I'm also having this issue. So far I've only tested it with themix-gui.

**Comment by actionless** [comment]
test it separately, otherwise issue gonna be closed as not enough info

**Comment by Stardust-kyun** [comment]
What exactly should I be looking for? What info do you need? I'm pretty sure this issue is happening to everyone.

**Comment by actionless** [comment]
this: https://github.com/nana-4/materia-theme/blob/master/HACKING.md#how-to-change-the-color-scheme

**Comment by Stardust-kyun** [comment]
It appears to also be an issue when manually running ./change-color.sh .

**Comment by actionless** [comment]
then, obviously, not a problem of themix app

**Comment by actionless** [comment]
btw those permanent random issues with inkscape/rsvg is the reason why oomox-gtk-theme (unlike Numix/Materia/Adwaita/etc) is not using any rendered assets

and for similar reasons, after it will be updated for gtk4 after gtk4 itself will get a bit more stable than now - i also planning to get rid of scss into direction of bare css

**Comment by actionless** [comment]
related ticket: https://github.com/nana-4/materia-theme/issues/594

**Comment by gregthwuen** [comment]
I had the same problem. Dug a little in `change_color.sh` and found out rendering with Inkscape can be disabled by providing `OPTION_FORCE_INKSCAPE` with seemingly any other value than `true`. Another problem was that the script expects the (deprecated?) binary name `rendersvg` instead of `resvg`. I fixed it with a symlink. Additionally, when rendering the GTK2 theme some assets caused errors that blocked further rendering. I deleted the according lines in `src/gtk-2.0/assets.txt` and rendering finally finished, but the GTK2 theme seems to be broken now. GTK3 theme works though.

While these are clearly upstream issues, Themix could at least warn of this. The first time I tried to render the theme, my X server was unresponsive for a few hours and finally crashed. Also, closing the Themix GUI doesn’t actually end the rendering processes, that’s the main issue for me.

**Comment by actionless** [comment]
feel free to submit a PR if that's a problem for you :)

you could also integrate an antivirus into themix gui, in case if somebody would put a virus into third-party plugin :D

**Comment by gregthwuen** [comment]
> you could also integrate an antivirus into themix gui, in case if somebody would put a virus into third-party plugin :D

That’s not serious, is it?

But I will see what I can do about the other issues. Happy holidays first of all :)

**Comment by joshuaelmbla** [comment]
@gregthwuen How did you build the symlink. I am using ln -s and it does not work. Resvg is a command.

**Comment by nPHYN1T3** [comment]
Sadly this has had me kinda scratching my head too. If I export oomox it's like 2 seconds and done. If I try materia it's hours, with every CPU core at 100% and nearly chewing up 512Gb of RAM.

**Comment by actionless** [comment]
@nPHYN1T3 https://github.com/themix-project/oomox/issues/387#issuecomment-880864245

**Comment by nPHYN1T3** [comment]
Yes I read the whole thread, doesn't change the fact it's borked. I used oomox years ago, then heard it was scrapped/abandoned. I just found this and gave it a try is all. When I thought maybe there was a mem leak I came looking for some answers and this thread was all that showed up for my terms/phrasing. While this is for the gui with the underlying script borked...this by extension is borked heh.

**Comment by actionless** [comment]
> Yes I read the whole thread, doesn't change the fact it's borked. I used oomox years ago, then heard it was scrapped/abandoned. I just found this and gave it a try is all. When I thought maybe there was a mem leak I came looking for some answers and this thread was all that showed up for my terms/phrasing. While this is for the gui with the underlying script borked...this by extension is borked heh.

then your logic is "borken" - materia is just a dependency - if it's not working itself, it's just not working
