### ISSUE TITLE
Unable to generate materia theme with latest inkscape on Arch Linux

### ISSUE THREAD

**Issue by adi1090x** [themix-project/oomox#389]
As mentioned in the Title, Can't generate Materia theme. Stuck at `rendering gtk2 assets...` and consumes all memory.
Probably the inkscape issue, 

- Using `themix-full` version from AUR
- Inkscape Version : Inkscape 1.1 (c4e8f9ed74, 2021-05-24)

Would you be able to have a look at this issue?

**Comment by actionless** [comment]
duplicate of https://github.com/themix-project/oomox/issues/387
