### ISSUE TITLE
Materia-dark theme unable to export

### ISSUE THREAD

**Issue by zion1004** [themix-project/oomox#391]
Oomox does not want to export materia-dark theme. Other themes export just fine.

`/opt/oomox/plugins/theme_materia/materia-theme/change_color.sh: line 297: ./render-assets.sh: Permission denied`

is the message I get
I'm running it on arch linux.
Installed using yay with the themix-full-git package.

**Comment by actionless** [comment]
you don't need no theme if you blind anyway

**Comment by zion1004** [comment]
im blind 🙈
