### ISSUE TITLE
Help with cli 

### ISSUE THREAD

**Issue by andrewschott** [themix-project/oomox#393]
Greetings.  

I installed this via git to a F34 WS install.  I followed the installation instructions off the readme/github landing page for the project.  
I am trying to automate a few things, hence the preference to the CLI interface.  Long story short I am using i3 and pywal to get most things themed, but need something for GTK, hence oomox.

On to the problem - I am having difficulty trying to figure out what needs to be executed.  I am running into either missing files or a gigantic scale brain fart.  So starting with the docs, I am seeing a reference to a shell script that either got moved (can't locate it) or removed -- change_color.sh.  From searching the issue tracker I see references by folks to oomox-cli (not seeing that one either).

So what am I doing wrong?
Thanks,
Andrew.

**Comment by actionless** [comment]
try to copy paste every command from readme again in the empty directory, idk what else to suggest, cli programs didn't dissapeared or moved

**Comment by actionless** [comment]
mb use find instead of ls :)

**Comment by andrewschott** [comment]
@actionless Thanks, that indeed did help quite nicely.  Sucks that the documentation hasn't had the TLC the rest of the software has.  Perhaps I can get some time to append some useful stuff from this lesson into it.  Sorry I had to pester you -- DuckDuckGo/Google/Bing were not helpful on this one.

@ Everyone else: For those that run into the same issue as I did, presuming you are using the same username as me and same spot for git pulls, the following command will use your xresources file and use the reverse preset to create a "oomox-xresources-reverse" theme that you can apply however, and each time you update it will just magically apply:

```
/home/andrew/workspace/git_repos/oomox/plugins/theme_oomox/change_color.sh /home/andrew/workspace/git_repos/oomox/scripted_colors/xresources/xresources-reverse
```

For those looking to see a (IMO) nicely strung together command to do i3, razer, discord, and GTK:

```
~/.local/bin/wal -f "$1" -o "/home/andrew/workspace/git_repos/oomox/plugins/theme_oomox/change_color.sh /home/andrew/workspace/git_repos/oomox/scripted_colors/xresources/xresources-reverse" && razer-cli -a && i3-msg restart && wal-discord; beautifuldiscord --css $HOME/.cache/wal-discord/style.css
```

The latter example can be passed any (py)wal theme. Edit if you wish to use it to generate one from a background image.

**Comment by actionless** [comment]
if you think you could improve the docs, please send a pull request

glad what it works as expected for you finally

**Comment by andrewschott** [comment]
I have been busy, but have some rudimentary updates I can get to you.  Once done I can do a pull request.  Thanks again, appreciate your patience and aid.

**Comment by actionless** [comment]
ok, looking forward to it :)

just a bit of sidenote on current state of distributions' support: i myself use Arch currently - so i making sure the newest version is always packaged there properly at AUR. but other ways of installation could be outdated due to current lack of maintainers. (for example for Fedora it was previously published on COPR by one of contributors for few years in a row in the past)
