### ISSUE TITLE
Exports Terminal Themes Wrong (base16 template)

### ISSUE THREAD

**Issue by The-Repo-Club** [themix-project/oomox#397]
the colors i have chosen are as below but the colors given are wrong

# Colors I chose
```
# black
color0  #21222c
color8  #6272a4

# red
color1  #ff5555
color9  #ff6e6e

# green
color2  #50fa7b
color10 #69ff94

# yellow
color3  #f1fa8c
color11 #ffffa5

# blue
color4  #bd93f9
color12 #d6acff

# magenta
color5  #ff79c6
color13 #ff92df

# cyan
color6  #8be9fd
color14 #a4ffff

# white
color7  #f8f8f2
color15 #ffffff
```
![image](https://user-images.githubusercontent.com/9284733/132730694-dff044ed-5ce2-43b4-aa07-e27e628938ff.png)

# Colors it gives me
```
# normal
color0 #282a36
color1 #ff6e6e
color2 #69ff94
color3 #ffffa5
color4 #acb6ff
color5 #ff92df
color6 #a4ffff
color7 #f8f8f2

# bright
color8 #909193
color9 #f1fa8c
color10 #21222c
color11 #6272a4
color12 #3c3e4a
color13 #f8f8f2
color14 #e49f69
color15 #ffffff
```

**Comment by The-Repo-Club** [comment]
# The colors it shows in the app
![image](https://user-images.githubusercontent.com/9284733/132731308-1237abac-7506-450c-bfe1-7adfa195876d.png)

# The colors it shows in the terminal
![image](https://user-images.githubusercontent.com/9284733/132731382-e45f2869-90c2-4395-8937-ca77a43608da.png)

**Comment by The-Repo-Club** [comment]
when using Export Xresources Theme button it will export correctly but when doing export base16 template then it shows as wrong as displayed below even for the xresources file in base16 

![image](https://user-images.githubusercontent.com/9284733/132733893-f42a68d4-7707-4af9-bf3f-e989ff52f126.png)

**Comment by actionless** [comment]
what exactly do you expect from my side? :)

i think you first need to visit the homepage of the template you currently using, and look into the template yourself to understand better how it works

**Comment by The-Repo-Club** [comment]
just had another look and it seems like the dracula base 16 theme the green imports as purple

**Comment by The-Repo-Club** [comment]
ill have a look at that base16 plugin and ill do a pull request after i fix it :)

**Comment by actionless** [comment]
unfortunately that's not possible - if you really interested in getting more terminal templates exported properly (similar to xresources) - i can help you to write the plugin for that

**Comment by actionless** [comment]
btw, i can also quickly refactor "Export Xresources" functionality into separate plugin, like those (https://github.com/themix-project/oomox/tree/master/plugins), so it will be much easier for you to use it a base for writing a plugin

right now you can use `base16` plugin as example as well, but it's too complicated in compare to other one

**Comment by The-Repo-Club** [comment]
ok sure that could work too :) its just wierd why that base16 for terminals dont work when i would of thought that they would if thats what the export is for

**Comment by The-Repo-Club** [comment]
if you could quickly make a plugin like the export Xresources that does the same ill work on editing it for other terminals and what not :)

**Comment by actionless** [comment]
here is it: https://github.com/themix-project/oomox/tree/export-xresources-plugin/plugins/export_xresources

**Comment by The-Repo-Club** [comment]
cheers :)

**Comment by actionless** [comment]
it assumed the rest of code being from that branch - to workaround you could replace it the line to `from oomox_gui.terminal import natural_sort`

**Comment by The-Repo-Club** [comment]
ya i just did that and its working now :) ill work on some more templates over the weekend for this :)

**Comment by actionless** [comment]
thanks, let me know if you need some help understanding how things work in the app or plugin API

but i hope what info from `export_xresources` and `base16` plugins should be enough for moving from basic into advanced :)

**Comment by The-Repo-Club** [comment]
[export_kitty](https://github.com/The-Repo-Club/oomox/tree/main/plugins/export_kitty) worked really good to make the kitty plugin :) next ill work on a few others :)

**Comment by actionless** [comment]
very nice work so quickly!

a hint, for stuff like selection_background or selection_foreground you can use not only TERMINAL_* vars but anything from theme_model: https://github.com/themix-project/oomox/blob/master/oomox_gui/theme_model.py

**Comment by actionless** [comment]
btw, since the plugin gonna have a lot of potentially updating templates - i was thinking what it might be better to maintain it as a submodule (same as it's done with base16 or spotify plugins, or materia/papirus/etc resources), https://github.com/themix-project/oomox/blob/master/.gitmodules

**Comment by The-Repo-Club** [comment]
[export_colorscheme](https://github.com/The-Repo-Club/oomox/tree/main/plugins/export_colorscheme) seems like i have found a better way to do this and can you templates instead of 1 plugin for each thing i wanna add thanks a million for the help :)

**Comment by actionless** [comment]
yup - looks much better now :)

let me know if you'll need any info or when you think plugin is ready to be shipped with the rest of the app

**Comment by The-Repo-Club** [comment]
other then just adding other templates to it then its ready now but ill be adding templates as i come up with them... people can add there own in ~/.config/oomox/colorscheme/templates/ too for local templates

**Comment by actionless** [comment]
nice!

i've extended the plugin api in the pre-1.14 version: https://github.com/themix-project/oomox/commit/3b9fa48b12a48d645fb526ef924c4f4e9b173620#diff-f32babd1a174274dfd0abf417ccc3f00a8655188a7c402aea4da7aa0d03b76d9R39

please also add those new fields to the plugin (you can add as many links as you like)

**Comment by The-Repo-Club** [comment]
cheers for that 
![image](https://user-images.githubusercontent.com/9284733/132957461-3e31d38a-edfa-4c4a-a4b3-7cfd74d6fcb8.png)

**Comment by The-Repo-Club** [comment]
i'm really hoping to get [Sardi](https://github.com/erikdubois/Sardi) and [Surfn](https://github.com/erikdubois/Surfn) icons into here just talking to the dev about it on telegram atm :)

**Comment by actionless** [comment]
great, mb also let's put @gusbemacbe in loop, he have a lot of experience in porting the icon themes to be supported by themix gui

**Comment by actionless** [comment]
(and btw feel free to create separate issues/discussions for those or any other topics, so it would be easier to find the conversations later, rather than in this unrelated ticket :) )

**Comment by The-Repo-Club** [comment]
@actionless by any chance does the Theme Colours View happen to get exported to be used inside OOMOX_TO_COLORSCHEME_TRANSLATION
