### ISSUE TITLE
Cannot install/build on Arch

### ISSUE THREAD

**Issue by Sensokaku** [themix-project/oomox#416]
everytime i've tried installing on arch from AUR i get

> if test -f po/es.po; then \
> 	msgmerge -U po/es.po po/oomox.pot; \
> else \
> 	msginit -o po/es.po -i po/oomox.pot; \
> fi
> msgmerge: error while opening "po/oomox.pot" for reading: No such file or directory
> make[1]: *** [po.mk:30: po/es.po] Error 1
> make[1]: Leaving directory '/home/sensokaku/.cache/pikaur/build/themix-gui-git/pkg/themix-gui-git/opt/oomox'
> make: *** [Makefile:30: install_gui] Error 2
> ==> ERROR: A failure occurred in package().
>     Aborting...

**Comment by actionless** [comment]
thanks for reporting!
