### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by OlaoluwaM** [themix-project/oomox#419]
I manually installed oomox but want to remove it completely. I cloned the repo and ran the `make` command. How can I revert this?

**Comment by actionless** [comment]
just remove `./distrib` dir, to which it installed

**Comment by ch3st3r08** [comment]
I just can't seem to find that directory. I've search in `$HOME`, in the repo I cloned, in `/opt`, am I missing something?

**Comment by actionless** [comment]
it's in the same directory where you ran the make command
