### ISSUE TITLE
LXQT: missing icon

### ISSUE THREAD

**Issue by FStefanni** [themix-project/oomox#425]
Hi,

I know that LXQT is not officially supported, but I have noticed that on my Debian installation,
LXQT with Openbox is missing:

- `folder-desktop.icon`
- `folder-desktop.png` / `folder-desktop.svg`

It could be nice to add them, just by "copying" the `network.png` / `network.icon` / `network.svg` files.

Regards.

**Comment by actionless** [comment]
oomox is gui app, for icons go to their own repository :)

**Comment by FStefanni** [comment]
Hi,

ok. The GUI shows me three icon sets.
Can you please put here the links to their repositories?
Thank you.

Regards.
