### ISSUE TITLE
configure: error: Invalid gnome-shell version: 3.36

### ISSUE THREAD

**Issue by stormshawn** [themix-project/oomox#430]
When trying to export a theme I am getting the following error:

![Screenshot from 2022-02-23 08-39-19](https://user-images.githubusercontent.com/38810328/155278497-55e0abde-8f2d-41ab-8353-c964a130959c.png)

Ubuntu 20.04.03
Gnome version: 3.36

**Comment by actionless** [comment]
this is repository for GUI app itself, for any error in particular theme or icons - post your error in their own repositories accordingly
