### ISSUE TITLE
GTK4 support?

### ISSUE THREAD

**Issue by tom-ricci** [themix-project/oomox#432]
I get #427, but I feel like GTK4 will eventually take off as more people use it by default, much like how GTK3 became the standard when people preferred GTK2 back in the day. Also, there's nothing else that can customize themes like oomix and I'd love to be able to use it for GTK4 :sweat_smile:

**Comment by actionless** [comment]
gtk3 was bringing killer-features over gtk2, namely hidpi and wayland support

while situation with gtk4 not as clear, especially considering experience of KDE+Qt5/Qt6 at the moment

BUT, all the lyrics aside - it's only up to themes to support gtk4 or not - oomox is only an UI to call theme plugins and manage palettes/previews

(or if you asking about oomox-gtk-theme - please let me know, i'll move this issue to its repo)

**Comment by tom-ricci** [comment]
No, I'm talking about oomox itself. Never knew oomox just edited existing themes, I always assumed it created a new theme based on the selected options in the UI. I'm assuming if a theme supports GTK4 and is edited in oomox the theme will still support GTK4?

**Comment by actionless** [comment]
there are currently 2 theme plugins, Materia and Oomox (Arc was recently removed), however Materia haven't received any updates for the last year so idk about its future

ok, then moving this to oomox-gtk-theme repo

**Comment by tom-ricci** [comment]
Ah, okay!

**Comment by actionless** [comment]
actually, i see it's already there: https://github.com/themix-project/oomox-gtk-theme/issues/75

**Comment by yavko** [comment]
I materia supports gtk4 so it would be nice if it could give the theme from it!
