### ISSUE TITLE
Themes do not apply to Firefox 98 and some apps

### ISSUE THREAD

**Issue by semka95** [themix-project/oomox#433]
OS: manjaro
<details>
  <summary>Oomox version</summary>
  
```
 local/themix-export-spotify-git 1.2.5.r4.g4c09ec3-1
    Export plugin for Themix GUI designer to apply color palettes to Spotify desktop player
local/themix-full-git 1.14-1
    Themix: GUI for generating different color variations of Materia, Oomox themes (GTK2, GTK3, Cinnamon, GNOME, MATE, Openbox, Xfwm), ArchDroid, Gnome-Colors, Numix, Papirus, Suru++ icons, and terminal palettes.
    Have a hack for HiDPI in GTK2.
local/themix-gui-git 1.14.r42.g4aec1bcd-1
    Plugin-based theme designer GUI for environments (like GTK2, GTK3, Cinnamon, GNOME, MATE, Openbox, Xfwm), icons and terminal palettes.
local/themix-icons-archdroid-git 1.0.2.r1.g775b8c2c0-1
    Archdroid icons plugin for Themix GUI designer
local/themix-icons-gnome-colors-git 5.5.5.r0.gcd8b05a-2
    Gnome-Colors icons plugin for Themix GUI designer
local/themix-icons-numix-git 21.10.31.r4.gb6c134d72-1
    Numix icons plugin for Themix GUI designer
local/themix-icons-papirus-git 20220302.r4.ge47623461d-1
    Papirus icons plugin for Themix GUI designer
local/themix-icons-suru-plus-aspromauros-git 3.0.r0.gd43a8ec4-1
    Suru++ Aspromauros icons plugin for Themix GUI designer
local/themix-icons-suru-plus-git 30.0.r2.g9bd895f32-1
    Suru++ icons plugin for Themix GUI designer
local/themix-import-images-git 1.14.r42.g4aec1bcd-1
    Import plugin for Themix GUI designer to get color palettes from the images
local/themix-plugin-base16-git 1.3.1.r1.g2744898-1
    Import and export plugin for Themix GUI designer to use color palettes from Base16 project
local/themix-theme-materia-git 20210322.r50.gaf63425f-1
    Materia theme plugin (GTK2, GTK3, GTK4, Cinnamon, GNOME, Metacity, Unity, Xfwm) for Themix GUI designer. Have a hack for HiDPI in GTK2.
local/themix-theme-oomox-git 1.12.2.r3.gaff8b363-1
    Oomox theme plugin (GTK2, GTK3, Cinnamon, Metacity, Openbox, Qt5ct, Qt6ct, Unity, Xfwm) for Themix GUI designer. Have a hack for HiDPI in GTK2.
```
  
</details>

This problem applicable to latest Firefox 98, and [Easyeffects](https://github.com/wwmm/easyeffects) for several versions (I don't remember when it started to appear). Maybe some other apps are affected.

**Problem Description:**
I generated new theme using latest version of themix, and this theme would not apply to Firefox 98 or Fasyeffects. When I try to apply it, using `gsettings set org.gnome.desktop.interface gtk-theme oomox-simple-rainbow`, some white theme applies, which looks like this:
<details>
  <summary>screenshots</summary>

![2022-03-15_21h41m53s_screenshot](https://user-images.githubusercontent.com/4162760/158449152-bf9ad0b2-ccc8-416c-8040-8e80d9149eac.png)

![2022-03-15_21h41m31s_screenshot](https://user-images.githubusercontent.com/4162760/158449192-2d516d03-b3ee-49f8-954d-f74d47c0a56a.png)
 
</details>

<details>
  <summary>This is how theme looks on other apps:</summary>

![2022-03-15_21h44m08s_screenshot](https://user-images.githubusercontent.com/4162760/158449345-c55c2f48-2954-4082-a081-d78968b9a963.png)

![2022-03-15_21h48m26s_screenshot](https://user-images.githubusercontent.com/4162760/158450081-f926bd61-4218-48c7-8822-8f4a11e3909b.png)

![2022-03-15_21h49m43s_screenshot](https://user-images.githubusercontent.com/4162760/158450135-98b52297-e697-449c-bcf4-434af151b0c1.png)
  
</details>

And after that I can't apply any other theme, it always stays white. I have to roll back to Firefox 97, switch to old theme, and then back to 98.
But this newly generated theme works fine with Firefox 97 and below, it also works in every GTK app I installed.
Old theme, which I generated at 9 Jan 2022, works with everything absolutely fine, including new Firefox and Easyeffects.
Here I attached two themes:
[new generated theme.zip](https://github.com/themix-project/oomox/files/8256038/new.generated.theme.zip)
[old generated theme.zip](https://github.com/themix-project/oomox/files/8256033/old.generated.theme.zip)

What could cause this strange behavior? Maybe some bug with GTK 4?

**Comment by actionless** [comment]
and easyeffects is indeed a gtk4 app, nothing related to firefox

**Comment by semka95** [comment]
> you must have some problem with firefox, works same as before on firefox 98
@actionless yeah, I think not only with Firefox, maybe something wrong with my system. I forgot to mention, I'm using wayland wm (sway).

**Comment by actionless** [comment]
try setting in `about:config`:

```
widget.non-native-theme.enabled = false
widget.content.allow-gtk-dark-theme = true
```

if it not helps try asking on firefox forums
