### ISSUE TITLE
Suspiciously long theme exporting

### ISSUE THREAD

**Issue by AkuBusshu** [themix-project/oomox#453]
I started exporting theme at approximately 15:00, first three steps went pretty quickly, but at 17:30 the exporting process is still stuck on `== Rendering GTK 2 assets...` and my computer is almost completely frozen too(drive indicator is still lighted up). I am exporting it to standart .themes folder on SSD with F2FS on it. Is this normal behaviour and if not, how can I fix that?

**Comment by Ultra980** [comment]
And stuck on the same thing, inkscape is using all of the resources (`sudo killall inkscape`, `killall inkscape`, `pkill inkscape`, `sudo pkill inkscape` didn't remove all of them, neither did `xkill` after clicking on oomox)

**Comment by actionless** [comment]
that's a duplicate of https://github.com/themix-project/oomox/issues/387

you can use Oomox theme style only until that would be fixed in Materia project
