### ISSUE TITLE
python 3.4 support EOL

### ISSUE THREAD

**Issue by cwendling** [themix-project/oomox#73]
It would be nice to have at least support for 3.4 (see e.g. #66 and #71).  Though, it might not be trivial to replace this one with older API, as both stdout and stderr are used.  Maybe only checking return code (and possibly using `set -e` if necessary) would be enough for the failing case, and so using `subprocess.check_output()` would be an option?

**Comment by actionless** [comment]
i want to drop all that `bash_preprocess` infrastructure and reimplement `random` and `xresources` themes in python side (but still leave bash version so they could be used from the command line)

**Comment by alexarnaud** [comment]
Do we really want to try to support python < 3.5 ? Debian stable 9 "Stretch" comes with Python 3.5 and Ubuntu LTS 16.04 also uses Python 3.5.

Best regards.

**Comment by actionless** [comment]
idk if there are any distros what currently using combination of python<3.5 and gtk>=3.18

**Comment by actionless** [comment]
after integrating travis linting on different python versions i've also noticed one more thing not available on python 3.4:
https://travis-ci.org/actionless/oomox/jobs/325350158#L8411

**Comment by actionless** [comment]
python 3.4 support has been restored however i would like to leave the discussion open

**Comment by actionless** [comment]
i am planning to increase minimal version to at least 3.5 to use native type hints

**Comment by actionless** [comment]
python 3.4 support will be dropped in release 1.10

**Comment by actionless** [comment]
for python 3.4 please use version 1.12.5.3 or older
for all the newer versions python 3.4 support won't be guaranteed and could be broken any time soon
